/* Source: Generated by ChatGPT */
package com.example.cydcompanion.ui.background

import androidx.compose.foundation.Canvas
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.drawscope.Stroke
import kotlinx.coroutines.delay
import kotlin.math.sin

@Composable
fun TokyoNeonBackdrop(content: @Composable () -> Unit) {
    var t by remember { mutableFloatStateOf(0f) }
    LaunchedEffect(Unit) {
        while (true) {
            delay(16)
            t += 0.016f
        }
    }

    Box(Modifier.fillMaxSize()) {
        Canvas(Modifier.fillMaxSize()) {
            val w = size.width
            val h = size.height

            // Inky base wash
            drawRect(Color(0xFF05040A))

            // Horizon
            val horizonY = h * 0.42f

            // Neon grid lines (perspective)
            val lines = 18
            val spacing = w / lines
            val drift = (sin(t * 0.7f) * 8f)

            // Vertical-ish lines to horizon
            for (i in -2..(lines + 2)) {
                val x = i * spacing + drift
                val x2 = w * 0.5f + (x - w * 0.5f) * 0.06f
                drawLine(
                    color = Color(0x3300E5FF),
                    start = Offset(x, h),
                    end = Offset(x2, horizonY),
                    strokeWidth = 2f
                )
            }

            // Horizontal perspective lines
            val bands = 22
            for (i in 0..bands) {
                val p = i / bands.toFloat()
                val y = horizonY + (h - horizonY) * (p * p)
                val alpha = (0.08f * (1f - p)) + 0.02f
                drawLine(
                    color = Color(0xFFFF2BD6).copy(alpha = alpha),
                    start = Offset(0f, y),
                    end = Offset(w, y),
                    strokeWidth = 2f
                )
            }

            // Subtle rain shimmer streaks
            val drops = 90
            val speed = 220f
            for (i in 0 until drops) {
                val seed = i * 37.73f
                val x = (seed * 19.91f) % w
                val y = ((seed * 7.13f) + (t * speed * 60f)) % h
                val len = 18f + (seed % 22f)
                drawLine(
                    color = Color(0x2200E5FF),
                    start = Offset(x, y),
                    end = Offset(x + 4f, y + len),
                    strokeWidth = 1.6f
                )
            }

            // Neon rim vignette
            drawRect(
                color = Color(0x1A8A5CFF),
                style = Stroke(width = 18f)
            )
        }

        content()
    }
}
