/* Source: Generated by ChatGPT */
package com.example.cydcompanion.domain

data class ConnectionState(
    val status: Status,
    val deviceName: String? = null,
    val rssi: Int? = null,
    val mtu: Int? = null,
    val uptimeSec: Int? = null
) {
    enum class Status { DISCONNECTED, SCANNING, CONNECTING, CONNECTED }
}

data class SessionSummary(
    val id: String,
    val startedAt: String,
    val records: Int,
    val warnings: Int,
    val notes: String
)

data class ConsoleLine(
    val ts: String,
    val level: Level,
    val tag: String,
    val msg: String
) {
    enum class Level { INFO, WARN, ERROR }
}

data class CydFile(
    val name: String,
    val path: String,
    val isDirectory: Boolean,
    val size: Long = 0
)

data class PacketLine(
    val seq: Long,
    val ms: Long,
    val type: Int,
    val subtype: Int,
    val len: Int,
    val rssi: Int,
    val channel: Int,
    val src: String,
    val dst: String,
    val bssid: String
)

// ---------------------------------------------------------------------------
// AI-Assisted Pentesting models (Phase 2)
// ---------------------------------------------------------------------------

/**
 * Parsed representation of a single EAPOL key frame (M1–M4).
 * Fields mirror the 802.11 Key Information bit layout; see FrameParser for offsets.
 */
data class EapolFrameInfo(
    val messageNum: Int,
    val rssi: Int,
    val timestampMs: Long,
    val keyInfo: Int,            // raw 16-bit Key Information word
    val keyLen: Int,
    val replayCounter: Long,
    val nonce: String,           // 32-byte nonce as uppercase hex
    val mic: String,             // 16-byte MIC as uppercase hex (zeroed in M1/M3)
    val hasMic: Boolean,         // Key Info bit 8
    val hasAck: Boolean,         // Key Info bit 7 — set in M1/M3
    val isSecure: Boolean,       // Key Info bit 9 — set in M3/M4
    val isPairwise: Boolean,     // Key Info bit 3
    val isEncryptedKD: Boolean,  // Key Info bit 12
    val keyDescVersion: Int,     // bits 0-2: 1=TKIP, 2=CCMP, 3=CCMP-256/GCMP
    val cipherHint: String,      // human-readable cipher from keyDescVersion
    val keyDescriptorType: Int,  // byte[0]: 0x02 = WPA/RSN
    val eapolHex: String,        // full EAPOL payload as hex (for forwarding to cracker)
    val frameHex: String         // full 802.11 frame as hex (includes addr1/2/3)
)

/**
 * Assembled target profile: network metadata + OUI-resolved vendors + captured EAPOL frames.
 * Built by [WifiCydRepository.fetchAiFrames] from the CYD's /api/ai/frames response.
 */
data class TargetProfile(
    val ssid: String,
    val bssid: String,
    val apOui: String,           // first 3 octets of BSSID  ("AA:BB:CC")
    val apVendor: String,        // OUI database lookup result
    val clientMac: String?,      // station MAC if a client was seen
    val staOui: String?,
    val staVendor: String?,
    val channel: Int,
    val rssi: Int,
    val auth: String,
    val eapolMask: Int,          // bitmask M1=bit0 M2=bit1 M3=bit2 M4=bit3
    val hasValidPair: Boolean,   // true if M1+M2 or M2+M3 captured
    val frames: List<EapolFrameInfo>
)

/**
 * AI-generated injection strategy for a [TargetProfile].
 * The fields map directly to the JSON schema the LLM is instructed to return.
 */
data class AiSuggestion(
    val injectionType: String,   // "deauth" | "disassoc" | "raw"
    val reasonCode: Int,         // 802.11 reason code (vendor-specific selection by AI)
    val deauthCount: Int,        // burst size
    val intervalMs: Int,         // ms between bursts
    val frameHex: String?,       // populated only when injectionType=="raw"
    val explanation: String,     // AI's vendor/chipset reasoning
    val rawJson: String          // full LLM response for debug display
)

/**
 * Snapshot of firmware runtime counters used to refine the next AI suggestion.
 * Populated from CYD /api/status.
 */
data class InjectionTelemetry(
    val packets: Long,
    val beacons: Long,
    val handshakes: Long,
    val sniffActive: Boolean,
    val lockChannel: Boolean,
    val yoinkState: String?,
    val yoinkTarget: String?,
    val yoinkDeauths: Long?,
    val yoinkHandshakes: Long?
)

// ---------------------------------------------------------------------------
// CrackBot-inspired: AI wordlist + CPU crack pipeline (Phase 2b)
// ---------------------------------------------------------------------------

/**
 * A single AI-generated password candidate.
 * [confidence] is the model's self-reported probability (0.0–1.0).
 * [rationale] is the model's reasoning (vendor default, SSID pattern, ISP scheme, etc.).
 */
data class WordlistCandidate(
    val password: String,
    val confidence: Float,
    val rationale: String
)

/**
 * A complete wordlist generated by [AiEngineClient.generateWordlist].
 * Contains the candidate list plus the model's overall cracking strategy narrative.
 */
data class GeneratedWordlist(
    val candidates: List<WordlistCandidate>,
    val strategy: String,        // model's explanation of the generation approach
    val confidence: Float,       // overall confidence the PSK is in this list (0.0–1.0)
    val rawJson: String
)

/**
 * Result of a [WpaVerifier.crack] run.
 */
data class CrackResult(
    val found: Boolean,
    val password: String?,
    val trialsCompleted: Int,
    val elapsedMs: Long,
    val error: String? = null
)

/**
 * Tracks a full CrackBot session: AI wordlist generation + CPU crack attempt.
 */
data class CrackSession(
    val profile: TargetProfile,
    val wordlist: GeneratedWordlist?,
    val result: CrackResult?,
    val exportPath: String? = null   // set after .22000 / .hccapx export
)
