/* Source: Generated by ChatGPT */
package com.example.cydcompanion.ui.theme

import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color

private val TokyoNeon = darkColorScheme(
    background = Color(0xFF05040A),   // inky
    onBackground = Color.White,
    surface = Color(0xFF0B0A14),      // deep indigo
    onSurface = Color.White,
    primary = Color(0xFF00E5FF),      // neon cyan
    onPrimary = Color.Black,
    secondary = Color(0xFFFF2BD6),    // neon magenta
    onSecondary = Color.White,
    tertiary = Color(0xFF8A5CFF),     // violet glow
    onTertiary = Color.White,
    outline = Color(0xFF2C2A3A),
    error = Color(0xFFFF3B3B),
    onError = Color.White
)

@Composable
fun TokyoNeonTheme(content: @Composable () -> Unit) {
    MaterialTheme(
        colorScheme = TokyoNeon,
        typography = TypographyTokyoNeon,
        content = content
    )
}
