/* Source: Generated by ChatGPT */
package com.example.cydcompanion.data

import android.graphics.Bitmap
import com.example.cydcompanion.domain.AiSuggestion
import com.example.cydcompanion.domain.ConnectionState
import com.example.cydcompanion.domain.ConsoleLine
import com.example.cydcompanion.domain.CydFile
import com.example.cydcompanion.domain.InjectionTelemetry
import com.example.cydcompanion.domain.PacketLine
import com.example.cydcompanion.domain.SessionSummary
import com.example.cydcompanion.domain.TargetProfile
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.StateFlow
import java.io.File

/**
 * Minimal contract your UI expects.
 */
interface CydRepository {
    val connection: StateFlow<ConnectionState>
    val console: Flow<ConsoleLine>
    val packets: Flow<PacketLine>
    val sessions: Flow<List<SessionSummary>>
    fun disconnect()

    /**
     * Connect via WiFi IP address
     */
    fun connectWifi(ipAddress: String)
    /**
     * Connect via USB serial (Android USB host OTG).
     */
    fun connectUsb()

    fun downloadTestFile()

    // File Explorer APIs
    val currentFiles: StateFlow<List<CydFile>>
    fun listFiles(path: String)
    fun downloadFile(file: CydFile)

    /** Download a remote file from CYD as bytes (for saving into the local vault). */
    suspend fun downloadFileBytes(file: CydFile): ByteArray?

    /** List files recursively from a CYD folder path. */
    suspend fun listFilesRecursive(path: String): List<CydFile>

    /** Toggle a short-lived on-device "Companion Sync" message while the app is pulling from CYD. */
    suspend fun setCompanionSync(active: Boolean): Boolean
    
    /**
     * OTA Update via WiFi
     */
    fun otaUpload(file: File): Flow<Float>

    // Control & Mirroring
    val screenMirror: StateFlow<Bitmap?>
    fun sendControlCommand(cmd: String, params: Map<String, Any> = emptyMap())

    // -----------------------------------------------------------------------
    // AI-Assisted Pentesting (Phase 2)
    // -----------------------------------------------------------------------

    /**
     * Fetch all EAPOL frames captured by the YOINK engine from the CYD, parse them,
     * resolve OUI vendors, and return the assembled [TargetProfile].
     * Returns null when the CYD reports no active target or is unreachable.
     */
    suspend fun fetchAiFrames(): TargetProfile?

    /**
     * Send a fully-formed raw 802.11 frame to the CYD radio.
     * [frameHex] is the hex string produced by the AI engine.
     * Returns true on success.
     */
    suspend fun injectRaw(channel: Int, frameHex: String): Boolean

    /**
     * Instruct the CYD to send an AI-parameterised deauthentication burst.
     * Returns true on success.
     */
    suspend fun injectDeauth(
        bssid: String,
        client: String = "FF:FF:FF:FF:FF:FF",
        reason: Int = 7,
        count: Int = 5,
        channel: Int = 0
    ): Boolean

    /**
     * Read runtime telemetry from CYD (/api/status) for post-injection AI refinement.
     */
    suspend fun fetchInjectionTelemetry(): InjectionTelemetry?
}
