/* Source: Generated by ChatGPT */
package com.example.cydcompanion.data

import android.graphics.Bitmap
import com.example.cydcompanion.domain.ConnectionState
import com.example.cydcompanion.domain.ConsoleLine
import com.example.cydcompanion.domain.CydFile
import com.example.cydcompanion.domain.InjectionTelemetry
import com.example.cydcompanion.domain.PacketLine
import com.example.cydcompanion.domain.SessionSummary
import com.example.cydcompanion.domain.TargetProfile
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.flow
import java.io.File
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import kotlin.random.Random

class FakeCydRepository : CydRepository {

    private val _conn = MutableStateFlow(
        ConnectionState(status = ConnectionState.Status.DISCONNECTED, deviceName = "CYD-WIFI")
    )
    override val connection: StateFlow<ConnectionState> = _conn.asStateFlow()

    override val sessions: Flow<List<SessionSummary>> = flow {
        val seed = listOf(
            SessionSummary("run_001", "2026-02-16 07:12", 1284, 3, "Baseline pass"),
            SessionSummary("run_002", "2026-02-16 07:48", 904, 0, "Clean"),
            SessionSummary("run_003", "2026-02-16 08:05", 2211, 7, "Spicy signal soup")
        )
        emit(seed)
    }

    override val console: Flow<ConsoleLine> = flow {
        val sdf = SimpleDateFormat("HH:mm:ss.SSS", Locale.US)
        var i = 0
        while (true) {
            delay(180)
            i++
            val lvl = when {
                i % 29 == 0 -> ConsoleLine.Level.ERROR
                i % 11 == 0 -> ConsoleLine.Level.WARN
                else -> ConsoleLine.Level.INFO
            }
            val tag = listOf("CYD", "WIFI", "UI", "CAP", "SYS").random()
            val msg = when (lvl) {
                ConsoleLine.Level.INFO -> listOf(
                    "Heartbeat OK",
                    "Frame parsed",
                    "Queue depth=${Random.nextInt(0, 12)}",
                    "RX bytes +${Random.nextInt(20, 240)}",
                    "Touch preset locked: #5"
                ).random()
                ConsoleLine.Level.WARN -> listOf(
                    "RSSI wobble detected",
                    "Retrying write",
                    "Dropped frame (simulated)",
                    "Clock drift +2ms"
                ).random()
                ConsoleLine.Level.ERROR -> listOf(
                    "Simulated fault: CRC mismatch",
                    "Simulated fault: buffer overrun",
                    "Simulated fault: stale session"
                ).random()
            }
            emit(ConsoleLine(ts = sdf.format(Date()), level = lvl, tag = tag, msg = msg))
        }
    }

    override val packets: Flow<PacketLine> = flow {
        var seq = 1L
        while (true) {
            delay(140)
            emit(
                PacketLine(
                    seq = seq++,
                    ms = System.currentTimeMillis() % 100000,
                    type = listOf(0, 1, 2).random(),
                    subtype = Random.nextInt(0, 15),
                    len = Random.nextInt(48, 420),
                    rssi = -30 - Random.nextInt(0, 60),
                    channel = listOf(1, 6, 11).random(),
                    src = "AA:BB:CC:${Random.nextInt(10, 99)}:22:33",
                    dst = "FF:FF:FF:FF:FF:FF",
                    bssid = "DE:AD:BE:EF:00:01"
                )
            )
        }
    }

    override fun disconnect() {}
    override fun connectWifi(ipAddress: String) {
        _conn.value = ConnectionState(ConnectionState.Status.CONNECTED, "WiFi: $ipAddress")
    }
    override fun connectUsb() {
        _conn.value = ConnectionState(ConnectionState.Status.CONNECTED, "USB: FAKE")
    }

    override fun downloadTestFile() {}

    // File Explorer APIs
    private val _currentFiles = MutableStateFlow<List<CydFile>>(emptyList())
    override val currentFiles: StateFlow<List<CydFile>> = _currentFiles.asStateFlow()

    override fun listFiles(path: String) {
        // Mock some files for the fake repository
        val mockFiles = if (path == "/") {
            listOf(
                CydFile("data", "/data", true, 0),
                CydFile("logs", "/logs", true, 0),
                CydFile("config.json", "/config.json", false, 1024)
            )
        } else if (path == "/data") {
            listOf(
                CydFile("run_001.csv", "/data/run_001.csv", false, 51200),
                CydFile("run_002.csv", "/data/run_002.csv", false, 12800)
            )
        } else {
            emptyList()
        }
        _currentFiles.value = mockFiles
    }

    override fun downloadFile(file: CydFile) {
        // No-op for fake
    }

    override suspend fun downloadFileBytes(file: CydFile): ByteArray? {
        if (file.isDirectory) return null
        return "FAKE_FILE:${file.path}\nSIZE=${file.size}\n".toByteArray(Charsets.UTF_8)
    }

    override suspend fun listFilesRecursive(path: String): List<CydFile> {
        // Fake implementation: return a few mock files
        return listOf(
            CydFile("file1.pcap", "$path/file1.pcap", false, 1024),
            CydFile("file2.csv", "$path/file2.csv", false, 512),
            CydFile("subfolder", "$path/subfolder", true, 0),
            CydFile("nested.txt", "$path/subfolder/nested.txt", false, 256)
        )
    }

    override suspend fun setCompanionSync(active: Boolean): Boolean {
        return true
    }

    override fun otaUpload(file: File): Flow<Float> = flow {
        for (i in 1..100) {
            delay(50)
            emit(i / 100f)
        }
    }

    private val _screenMirror = MutableStateFlow<Bitmap?>(null)
    override val screenMirror: StateFlow<Bitmap?> = _screenMirror.asStateFlow()

    override fun sendControlCommand(cmd: String, params: Map<String, Any>) {
        // Mocking control command
    }

    // AI stubs — return null/false so the UI shows "no active target" in fake mode
    override suspend fun fetchAiFrames(): TargetProfile? = null
    override suspend fun injectRaw(channel: Int, frameHex: String): Boolean = false
    override suspend fun injectDeauth(
        bssid: String, client: String, reason: Int, count: Int, channel: Int
    ): Boolean = false

    override suspend fun fetchInjectionTelemetry(): InjectionTelemetry? = InjectionTelemetry(
        packets = 1532,
        beacons = 401,
        handshakes = 2,
        sniffActive = true,
        lockChannel = true,
        yoinkState = "targeting",
        yoinkTarget = "DemoAP",
        yoinkDeauths = 14,
        yoinkHandshakes = 2
    )

    suspend fun simulateConnectionCycle() {
        _conn.emit(ConnectionState(ConnectionState.Status.CONNECTING, "CYD-WIFI"))
        delay(1200)
        _conn.emit(ConnectionState(ConnectionState.Status.CONNECTED, "CYD-WIFI", rssi = -53, mtu = 185, uptimeSec = 42))

        // jitter
        var up = 42
        while (true) {
            delay(1200)
            up += 1
            _conn.emit(ConnectionState(ConnectionState.Status.CONNECTED, "CYD-NEON", rssi = -48 - Random.nextInt(0, 18), mtu = 185, uptimeSec = up))
        }
    }
}
