/* Source: Generated by ChatGPT */
package com.example.cydcompanion.data

import android.app.PendingIntent
import android.content.Context
import android.content.Intent
import android.os.Environment
import android.graphics.Bitmap
import android.hardware.usb.UsbManager
import com.example.cydcompanion.ai.FrameParser
import com.example.cydcompanion.ai.InjectionDispatcher
import com.example.cydcompanion.ai.OuiDatabase
import com.example.cydcompanion.domain.AiSuggestion
import com.example.cydcompanion.domain.ConnectionState
import com.example.cydcompanion.domain.ConsoleLine
import com.example.cydcompanion.domain.CydFile
import com.example.cydcompanion.domain.EapolFrameInfo
import com.example.cydcompanion.domain.InjectionTelemetry
import com.example.cydcompanion.domain.PacketLine
import com.example.cydcompanion.domain.SessionSummary
import com.example.cydcompanion.domain.TargetProfile
import kotlinx.coroutines.*
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import okhttp3.*
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.RequestBody.Companion.asRequestBody
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONObject
import java.io.File
import java.io.IOException
import java.net.URLDecoder
import java.text.SimpleDateFormat
import java.util.*
import java.util.concurrent.TimeUnit
import java.io.ByteArrayOutputStream
import com.hoho.android.usbserial.driver.UsbSerialPort
import com.hoho.android.usbserial.driver.UsbSerialProber

class WifiCydRepository(private val appContext: Context) : CydRepository {
    private enum class Transport { NONE, WIFI, USB }

    init {
        // Lazy-load OUI database once on construction; runs in Dispatchers.IO at first use
        OuiDatabase.init(appContext)
    }

    private val client = OkHttpClient.Builder()
        .connectTimeout(2, TimeUnit.SECONDS)
        .readTimeout(30, TimeUnit.SECONDS) // Longer for OTA
        .build()

    private val scope = CoroutineScope(SupervisorJob() + Dispatchers.IO)

    private val _connection = MutableStateFlow(ConnectionState(ConnectionState.Status.DISCONNECTED, null))
    override val connection: StateFlow<ConnectionState> = _connection.asStateFlow()

    private val _console = MutableSharedFlow<ConsoleLine>(extraBufferCapacity = 256)
    override val console: Flow<ConsoleLine> = _console.asSharedFlow()
    private val _packets = MutableSharedFlow<PacketLine>(extraBufferCapacity = 512)
    override val packets: Flow<PacketLine> = _packets.asSharedFlow()

    private val _currentFiles = MutableStateFlow<List<CydFile>>(emptyList())
    override val currentFiles: StateFlow<List<CydFile>> = _currentFiles.asStateFlow()

    private val _screenMirror = MutableStateFlow<Bitmap?>(null)
    override val screenMirror: StateFlow<Bitmap?> = _screenMirror.asStateFlow()

    override val sessions: Flow<List<SessionSummary>> = flowOf(emptyList())

    private var targetIp: String? = null
    private var transport: Transport = Transport.NONE
    private var consolePollJob: Job? = null
    private var packetPollJob: Job? = null
    private var lastConsoleSeq: Long = 0
    private var lastPacketSeq: Long = 0
    private var consolePollFailStreak: Int = 0
    private val usbManager = appContext.getSystemService(Context.USB_SERVICE) as UsbManager
    private var usbPort: UsbSerialPort? = null
    private var usbDeviceName: String? = null
    private val usbRpcMutex = Mutex()
    private val usbRxBuf = StringBuilder()
    private var usbRpcId = 1

    override fun disconnect() {
        targetIp = null
        transport = Transport.NONE
        consolePollJob?.cancel()
        packetPollJob?.cancel()
        runCatching { usbPort?.close() }
        usbPort = null
        usbDeviceName = null
        usbRxBuf.clear()
        lastConsoleSeq = 0
        lastPacketSeq = 0
        _connection.value = ConnectionState(ConnectionState.Status.DISCONNECTED, null)
        logInfo("WIFI", "Disconnected")
    }

    override fun connectWifi(ipAddress: String) {
        runCatching { usbPort?.close() }
        usbPort = null
        usbDeviceName = null
        val cleanIp = ipAddress.trim()
            .removePrefix("http://")
            .removePrefix("https://")
            .substringBefore("/")
            .substringBefore(":")
        if (cleanIp.isBlank()) {
            logError("WIFI", "Invalid IP/host")
            _connection.value = ConnectionState(ConnectionState.Status.DISCONNECTED, null)
            return
        }
        targetIp = cleanIp
        transport = Transport.WIFI
        _connection.value = ConnectionState(ConnectionState.Status.CONNECTING, ipAddress)

        scope.launch {
            try {
                val request = Request.Builder().url(baseUrl("/api/status")).build()
                client.newCall(request).execute().use { response ->
                    if (response.isSuccessful) {
                        val body = response.body?.string().orEmpty()
                        val obj = JSONObject(body)
                        val deviceName = obj.optString("name", cleanIp)
                        _connection.value = ConnectionState(ConnectionState.Status.CONNECTED, deviceName)
                        logInfo("WIFI", "Connected to $cleanIp:8080")
                        consolePollFailStreak = 0
                        startConsolePolling()
                        startPacketPolling()
                    } else {
                        throw IOException("Failed to connect: ${response.code}")
                    }
                }
            } catch (e: Exception) {
                _connection.value = ConnectionState(ConnectionState.Status.DISCONNECTED, null)
                logError("WIFI", "Connection failed: ${e.message}")
            }
        }
    }

    override fun connectUsb() {
        targetIp = null
        consolePollJob?.cancel()
        packetPollJob?.cancel()
        lastConsoleSeq = 0
        lastPacketSeq = 0
        usbRxBuf.clear()
        _connection.value = ConnectionState(ConnectionState.Status.CONNECTING, "USB")

        scope.launch {
            try {
                val drivers = UsbSerialProber.getDefaultProber().findAllDrivers(usbManager)
                if (drivers.isEmpty()) {
                    _connection.value = ConnectionState(ConnectionState.Status.DISCONNECTED, null)
                    logError("USB", "No USB serial device found. Connect CYD via OTG USB-C.")
                    return@launch
                }
                val driver = drivers.first()
                val device = driver.device
                if (!usbManager.hasPermission(device)) {
                    val pi = PendingIntent.getBroadcast(
                        appContext,
                        0,
                        Intent("com.example.cydcompanion.USB_PERMISSION"),
                        PendingIntent.FLAG_IMMUTABLE
                    )
                    usbManager.requestPermission(device, pi)
                    _connection.value = ConnectionState(ConnectionState.Status.DISCONNECTED, null)
                    logError("USB", "Grant USB permission then tap USB Link again.")
                    return@launch
                }
                val conn = usbManager.openDevice(device)
                if (conn == null) {
                    _connection.value = ConnectionState(ConnectionState.Status.DISCONNECTED, null)
                    logError("USB", "Failed to open USB device.")
                    return@launch
                }
                val port = driver.ports.firstOrNull()
                if (port == null) {
                    conn.close()
                    _connection.value = ConnectionState(ConnectionState.Status.DISCONNECTED, null)
                    logError("USB", "No serial port on USB device.")
                    return@launch
                }
                port.open(conn)
                port.setParameters(115200, 8, UsbSerialPort.STOPBITS_1, UsbSerialPort.PARITY_NONE)
                runCatching { port.setDTR(true); port.setRTS(true) }
                usbPort = port
                transport = Transport.USB
                usbDeviceName = device.productName ?: device.deviceName ?: "CYD-USB"
                val status = usbRpc("status")
                val name = status?.optString("name")?.takeIf { it.isNotBlank() } ?: usbDeviceName
                _connection.value = ConnectionState(ConnectionState.Status.CONNECTED, name)
                logInfo("USB", "Connected over USB serial: $name")
                startConsolePolling()
                startPacketPolling()
            } catch (e: Exception) {
                runCatching { usbPort?.close() }
                usbPort = null
                transport = Transport.NONE
                _connection.value = ConnectionState(ConnectionState.Status.DISCONNECTED, null)
                logError("USB", "Connection failed: ${e.message}")
            }
        }
    }

    override fun sendControlCommand(cmd: String, params: Map<String, Any>) {
        if (transport == Transport.USB) {
            scope.launch {
                val payload = JSONObject().apply {
                    put("name", cmd)
                    params.forEach { (k, v) ->
                        when (v) {
                            is Boolean -> put(k, v)
                            is Number -> put(k, v)
                            else -> put(k, v.toString())
                        }
                    }
                }
                val response = usbRpc("control", payload)
                if (response?.optBoolean("ok", false) == true) {
                    logInfo("USB", "CTRL $cmd OK")
                } else {
                    logError("USB", "CTRL $cmd failed: ${response?.optString("error", "no response")}")
                }
            }
            return
        }
        if (targetIp == null) return
        scope.launch {
            val json = JSONObject().apply {
                put("cmd", cmd)
                params.forEach { (k, v) -> put(k, v) }
            }
            val body = json.toString().toRequestBody("application/json".toMediaType())
            val request = Request.Builder().url(baseUrl("/api/control")).post(body).build()
            try {
                client.newCall(request).execute().use { response ->
                    val payload = response.body?.string().orEmpty()
                    if (response.isSuccessful) logInfo("CMD", "$cmd OK")
                    else logError("CMD", "$cmd failed: ${response.code} $payload")
                }
            } catch (e: Exception) {
                logError("CMD", "Request error: ${e.message}")
            }
        }
    }

    override fun listFiles(path: String) {
        scope.launch {
            val files = listFilesCompat(path)
            _currentFiles.value = files.sortedWith(
                compareBy<CydFile>({ !it.isDirectory }, { it.name.lowercase(Locale.US) })
            )
            logInfo("FS", "Listed ${files.size} items in $path")
        }
    }

    override fun downloadFile(file: CydFile) {
        scope.launch {
            val bytes = downloadFileBytes(file)
            if (bytes == null) {
                logError("FS", "Download failed for ${file.path}")
                return@launch
            }
            try {
                val downloadsRoot = File(
                    appContext.getExternalFilesDir(Environment.DIRECTORY_DOWNLOADS),
                    "cyd_downloads"
                )
                downloadsRoot.mkdirs()
                val safeName = if (file.name.isBlank()) "download.bin" else file.name
                val outFile = File(downloadsRoot, safeName)
                outFile.writeBytes(bytes)
                logInfo("FS", "Saved ${bytes.size} bytes to ${outFile.absolutePath}")
            } catch (e: Exception) {
                logError("FS", "Download save error: ${e.message}")
            }
        }
    }

    override suspend fun downloadFileBytes(file: CydFile): ByteArray? = withContext(Dispatchers.IO) {
        if (file.isDirectory) return@withContext null
        if (transport == Transport.USB) {
            return@withContext downloadFileBytesUsb(file)
        }
        val ip = targetIp ?: return@withContext null

        val (fsToken, fsPath) = splitRepoPath(file.path)
        val apiUrl = HttpUrl.Builder()
            .scheme("http")
            .host(ip)
            .port(8080)
            .addPathSegment("download")
            .addQueryParameter("fs", fsToken)
            .addQueryParameter("path", fsPath)
            .build()

        // Newer app protocol first
        val fromApi = try {
            client.newCall(Request.Builder().url(apiUrl).build()).execute().use { response ->
                if (!response.isSuccessful) {
                    null
                } else {
                    response.body?.bytes()
                }
            }
        } catch (_: Exception) {
            null
        }
        if (fromApi != null) return@withContext fromApi

        // Firmware-compatible SD endpoint fallback
        if (!fsToken.equals("sd", true)) {
            logError("FS", "Download bytes failed: unsupported fs=$fsToken on this firmware")
            return@withContext null
        }
        val sdUrl = HttpUrl.Builder()
            .scheme("http")
            .host(ip)
            .port(8080)
            .addPathSegment("sd")
            .addPathSegment("get")
            .addQueryParameter("path", normalizeFsPath(fsPath))
            .build()

        return@withContext try {
            client.newCall(Request.Builder().url(sdUrl).build()).execute().use { response ->
                if (!response.isSuccessful) {
                    logError("FS", "Download bytes failed: HTTP ${response.code}")
                    null
                } else {
                    response.body?.bytes()
                }
            }
        } catch (e: Exception) {
            logError("FS", "Download bytes error: ${e.message}")
            null
        }
    }

    override suspend fun listFilesRecursive(path: String): List<CydFile> = withContext(Dispatchers.IO) {
        val result = mutableListOf<CydFile>()
        val queue = mutableListOf(path)
        val visited = mutableSetOf<String>()

        while (queue.isNotEmpty()) {
            val currentPath = queue.removeAt(0)
            if (currentPath in visited) continue
            visited.add(currentPath)
            val children = listFilesCompat(currentPath)
            children.forEach { file ->
                result.add(file)
                if (file.isDirectory) queue.add(file.path)
            }
        }
        result
    }

    override suspend fun setCompanionSync(active: Boolean): Boolean = withContext(Dispatchers.IO) {
        if (transport == Transport.USB) return@withContext false
        val ip = targetIp ?: return@withContext false
        val url = HttpUrl.Builder()
            .scheme("http")
            .host(ip)
            .port(8080)
            .addPathSegment("api")
            .addPathSegment("companion")
            .addPathSegment("sync")
            .addQueryParameter("active", if (active) "1" else "0")
            .build()

        return@withContext try {
            client.newCall(Request.Builder().url(url).get().build()).execute().use { resp ->
                resp.isSuccessful
            }
        } catch (_: Exception) {
            false
        }
    }

    override fun downloadTestFile() {}

    override fun otaUpload(file: File): Flow<Float> = callbackFlow {
        if (targetIp == null) throw IOException("Not connected via WiFi")
        logInfo("OTA", "Starting upload: ${file.name} (${file.length()} bytes)")
        trySend(0.0f)

        val requestBody = MultipartBody.Builder()
            .setType(MultipartBody.FORM)
            .addFormDataPart("firmware", file.name, file.asRequestBody("application/octet-stream".toMediaType()))
            .build()

        val request = Request.Builder()
            .url(baseUrl("/ota"))
            .post(requestBody)
            .build()

        val call = client.newCall(request)

        scope.launch {
            try {
                val response = withContext(Dispatchers.IO) { call.execute() }
                if (response.isSuccessful) {
                    logInfo("OTA", "Upload complete! Device is rebooting...")
                    trySend(1.0f)
                } else {
                    logError("OTA", "Upload failed: ${response.code}")
                    close(IOException("Server returned ${response.code}"))
                }
            } catch (e: Exception) {
                logError("OTA", "OTA Error: ${e.message}")
                close(e)
            } finally {
                channel.close()
            }
        }

        awaitClose { call.cancel() }
    }

    private fun logInfo(tag: String, msg: String) {
        _console.tryEmit(ConsoleLine(ts = nowTs(), level = ConsoleLine.Level.INFO, tag = tag, msg = msg))
    }

    private fun logError(tag: String, msg: String) {
        _console.tryEmit(ConsoleLine(ts = nowTs(), level = ConsoleLine.Level.ERROR, tag = tag, msg = msg))
    }

    private fun nowTs(): String = SimpleDateFormat("HH:mm:ss", Locale.US).format(Date())

    private fun startConsolePolling() {
        consolePollJob?.cancel()
        lastConsoleSeq = 0
        consolePollJob = scope.launch {
            while (isActive && targetIp != null && _connection.value.status == ConnectionState.Status.CONNECTED) {
                pollConsoleOnce()
                delay(450)
            }
        }
    }

    private fun startPacketPolling() {
        packetPollJob?.cancel()
        lastPacketSeq = 0
        packetPollJob = scope.launch {
            while (isActive && targetIp != null && _connection.value.status == ConnectionState.Status.CONNECTED) {
                pollPacketsOnce()
                delay(260)
            }
        }
    }

    private suspend fun pollConsoleOnce() {
        if (transport == Transport.USB) {
            pollConsoleOnceUsb()
            return
        }
        val ip = targetIp ?: return
        val url = HttpUrl.Builder()
            .scheme("http")
            .host(ip)
            .port(8080)
            .addPathSegment("api")
            .addPathSegment("console")
            .addQueryParameter("since", lastConsoleSeq.toString())
            .addQueryParameter("limit", "80")
            .build()

        try {
            client.newCall(Request.Builder().url(url).build()).execute().use { response ->
                if (!response.isSuccessful) return@use
                consolePollFailStreak = 0
                val body = response.body?.string().orEmpty()
                val obj = JSONObject(body)
                val lines = obj.optJSONArray("lines") ?: return@use
                for (i in 0 until lines.length()) {
                    val line = lines.getJSONObject(i)
                    val seq = line.optLong("seq", 0L)
                    if (seq > lastConsoleSeq) lastConsoleSeq = seq
                    val level = when (line.optString("level", "INFO").uppercase(Locale.US)) {
                        "ERROR" -> ConsoleLine.Level.ERROR
                        "WARN" -> ConsoleLine.Level.WARN
                        else -> ConsoleLine.Level.INFO
                    }
                    _console.tryEmit(
                        ConsoleLine(
                            ts = nowTs(),
                            level = level,
                            tag = line.optString("tag", "WEB"),
                            msg = line.optString("msg", "")
                        )
                    )
                }
            }
        } catch (_: Exception) {
            // Keep polling; transient network failures are expected.
            consolePollFailStreak++
            if (consolePollFailStreak == 6) {
                logError(
                    "WIFI",
                    "Console link unstable. If sniffing, connect phone WiFi to CYD-LIVE and use 192.168.4.1"
                )
            }
        }
    }

    private suspend fun pollPacketsOnce() {
        if (transport == Transport.USB) {
            pollPacketsOnceUsb()
            return
        }
        val ip = targetIp ?: return
        val url = HttpUrl.Builder()
            .scheme("http")
            .host(ip)
            .port(8080)
            .addPathSegment("api")
            .addPathSegment("packets")
            .addQueryParameter("since", lastPacketSeq.toString())
            .addQueryParameter("limit", "150")
            .build()

        try {
            client.newCall(Request.Builder().url(url).build()).execute().use { response ->
                if (!response.isSuccessful) return@use
                val body = response.body?.string().orEmpty()
                val obj = JSONObject(body)
                val lines = obj.optJSONArray("lines") ?: return@use
                for (i in 0 until lines.length()) {
                    val line = lines.getJSONObject(i)
                    val seq = line.optLong("seq", 0L)
                    if (seq > lastPacketSeq) lastPacketSeq = seq
                    _packets.tryEmit(
                        PacketLine(
                            seq = seq,
                            ms = line.optLong("ms", 0L),
                            type = line.optInt("type", -1),
                            subtype = line.optInt("subtype", -1),
                            len = line.optInt("len", 0),
                            rssi = line.optInt("rssi", -127),
                            channel = line.optInt("ch", 0),
                            src = line.optString("src", ""),
                            dst = line.optString("dst", ""),
                            bssid = line.optString("bssid", "")
                        )
                    )
                }
            }
        } catch (_: Exception) {
            // Keep polling; transient failures are expected.
        }
    }

    private fun splitRepoPath(repoPathRaw: String): Pair<String, String> {
        var p = repoPathRaw.trim()
        if (p.isEmpty()) p = "/sd"
        if (!p.startsWith("/")) p = "/$p"

        return if (p.equals("/lfs", true) || p.startsWith("/lfs/")) {
            val inner = p.removePrefix("/lfs").ifBlank { "/" }
            "lfs" to normalizeFsPath(inner)
        } else {
            val inner = p.removePrefix("/sd").ifBlank { "/" }
            "sd" to normalizeFsPath(inner)
        }
    }

    private fun toRepoPath(fsTokenRaw: String, fsPathRaw: String): String {
        val fsPrefix = if (fsTokenRaw.equals("lfs", true)) "/lfs" else "/sd"
        val fsPath = normalizeFsPath(fsPathRaw)
        return if (fsPath == "/") fsPrefix else fsPrefix + fsPath
    }

    private fun normalizeFsPath(pathRaw: String): String {
        var p = pathRaw.trim()
        if (p.isEmpty()) p = "/"
        if (!p.startsWith("/")) p = "/$p"
        return p
    }

    private fun baseUrl(path: String): String {
        val ip = targetIp ?: "0.0.0.0"
        return "http://$ip:8080$path"
    }

    // -------------------------------------------------------------------------
    // File listing compatibility layer
    // -------------------------------------------------------------------------

    private suspend fun listFilesCompat(path: String): List<CydFile> = withContext(Dispatchers.IO) {
        if (transport == Transport.USB) {
            return@withContext listFilesViaUsb(path)
        }
        val ip = targetIp ?: return@withContext emptyList()
        val (fsToken, fsPath) = splitRepoPath(path)

        // Preferred API (if firmware supports it)
        listFilesViaApi(ip, fsToken, fsPath)?.let { return@withContext it }

        // Firmware fallback: SD file-manager HTML
        if (!fsToken.equals("sd", true)) {
            logError("FS", "List failed: fs=$fsToken unsupported by current firmware")
            return@withContext emptyList()
        }
        return@withContext listFilesViaSdHtml(ip, fsPath)
    }

    private fun listFilesViaApi(ip: String, fsToken: String, fsPath: String): List<CydFile>? {
        val url = HttpUrl.Builder()
            .scheme("http")
            .host(ip)
            .port(8080)
            .addPathSegment("api")
            .addPathSegment("list")
            .addQueryParameter("fs", fsToken)
            .addQueryParameter("path", fsPath)
            .build()

        return try {
            client.newCall(Request.Builder().url(url).build()).execute().use { response ->
                if (!response.isSuccessful) return null
                val jsonStr = response.body?.string().orEmpty()
                val root = JSONObject(jsonStr)
                val items = root.optJSONArray("items") ?: return emptyList()
                val out = mutableListOf<CydFile>()
                for (i in 0 until items.length()) {
                    val item = items.getJSONObject(i)
                    val itemPath = item.optString("path", "/")
                    val itemFs = root.optString("fs", fsToken)
                    val name = item.optString("name").ifBlank {
                        itemPath.substringAfterLast('/', itemPath)
                    }
                    out.add(
                        CydFile(
                            name = name,
                            path = toRepoPath(itemFs, itemPath),
                            isDirectory = item.optBoolean("dir", false),
                            size = item.optLong("size", 0L)
                        )
                    )
                }
                out
            }
        } catch (_: Exception) {
            null
        }
    }

    private fun listFilesViaSdHtml(ip: String, fsPath: String): List<CydFile> {
        val normalized = normalizeFsPath(fsPath)
        val url = HttpUrl.Builder()
            .scheme("http")
            .host(ip)
            .port(8080)
            .addPathSegment("sd")
            .addQueryParameter("path", normalized)
            .build()

        return try {
            client.newCall(Request.Builder().url(url).build()).execute().use { response ->
                if (!response.isSuccessful) {
                    logError("FS", "List failed: HTTP ${response.code}")
                    return emptyList()
                }
                val html = response.body?.string().orEmpty()
                parseSdHtmlDirectoryRows(html)
            }
        } catch (e: Exception) {
            logError("FS", "List failed: ${e.message}")
            emptyList()
        }
    }

    private fun parseSdHtmlDirectoryRows(html: String): List<CydFile> {
        val rows = Regex(
            "<tr><td>(.*?)</td><td>(dir|file)</td><td>(\\d+)</td><td>(.*?)</td></tr>",
            setOf(RegexOption.IGNORE_CASE, RegexOption.DOT_MATCHES_ALL)
        ).findAll(html)

        val out = mutableListOf<CydFile>()
        rows.forEach { m ->
            val name = decodeHtmlEntities(m.groupValues[1]).trim()
            val type = m.groupValues[2].lowercase(Locale.US)
            val size = m.groupValues[3].toLongOrNull() ?: 0L
            val actions = m.groupValues[4]

            val pathEncoded = if (type == "dir") {
                Regex("href='/sd\\?path=([^']+)'", RegexOption.IGNORE_CASE).find(actions)?.groupValues?.getOrNull(1)
            } else {
                Regex("href='/sd/get\\?path=([^']+)'", RegexOption.IGNORE_CASE).find(actions)?.groupValues?.getOrNull(1)
            } ?: return@forEach

            val fullPath = decodeUrl(pathEncoded)
            if (fullPath.isBlank() || fullPath == "/") return@forEach
            out.add(
                CydFile(
                    name = if (name.isBlank()) fullPath.substringAfterLast('/', fullPath) else name,
                    path = toRepoPath("sd", fullPath),
                    isDirectory = type == "dir",
                    size = size
                )
            )
        }
        return out
    }

    private fun decodeUrl(raw: String): String =
        runCatching { URLDecoder.decode(raw, Charsets.UTF_8.name()) }.getOrElse { raw }

    private fun decodeHtmlEntities(raw: String): String {
        return raw
            .replace("&lt;", "<")
            .replace("&gt;", ">")
            .replace("&amp;", "&")
            .replace("&quot;", "\"")
            .replace("&#39;", "'")
    }

    private suspend fun listFilesViaUsb(path: String): List<CydFile> = withContext(Dispatchers.IO) {
        val (fsToken, fsPath) = splitRepoPath(path)
        if (!fsToken.equals("sd", true)) {
            logError("USB", "Only /sd is supported over USB at this time.")
            return@withContext emptyList()
        }
        val rsp = usbRpc("list", JSONObject().put("path", fsPath)) ?: return@withContext emptyList()
        if (!rsp.optBoolean("ok", false)) return@withContext emptyList()
        val items = rsp.optJSONArray("items") ?: return@withContext emptyList()
        val out = mutableListOf<CydFile>()
        for (i in 0 until items.length()) {
            val item = items.optJSONObject(i) ?: continue
            val fullPath = item.optString("path", "")
            val name = item.optString("name", fullPath.substringAfterLast('/', fullPath))
            out.add(
                CydFile(
                    name = name,
                    path = toRepoPath("sd", fullPath),
                    isDirectory = item.optBoolean("dir", false),
                    size = item.optLong("size", 0L)
                )
            )
        }
        out
    }

    private suspend fun downloadFileBytesUsb(file: CydFile): ByteArray? = withContext(Dispatchers.IO) {
        val (fsToken, fsPath) = splitRepoPath(file.path)
        if (!fsToken.equals("sd", true)) {
            logError("USB", "Download supports only /sd paths on USB.")
            return@withContext null
        }
        val begin = usbRpc("download_begin", JSONObject().put("path", fsPath)) ?: return@withContext null
        if (!begin.optBoolean("ok", false)) return@withContext null
        val token = begin.optString("token", "")
        val total = begin.optLong("size", 0L)
        if (token.isBlank()) return@withContext null

        val out = ByteArrayOutputStream(if (total > 0) total.toInt() else 4096)
        var offset = 0L
        while (true) {
            val chunk = usbRpc(
                "download_chunk",
                JSONObject()
                    .put("token", token)
                    .put("offset", offset)
                    .put("max", 192)
            ) ?: break
            if (!chunk.optBoolean("ok", false)) break
            val hex = chunk.optString("hex", "")
            val bytes = decodeHex(hex)
            if (bytes.isNotEmpty()) out.write(bytes)
            val eof = chunk.optBoolean("eof", false)
            offset = chunk.optLong("offset", offset) + bytes.size
            if (eof) break
            if (bytes.isEmpty()) break
        }
        usbRpc("download_end", JSONObject().put("token", token))
        out.toByteArray()
    }

    private suspend fun pollConsoleOnceUsb() {
        val rsp = usbRpc(
            "console",
            JSONObject()
                .put("since", lastConsoleSeq)
                .put("limit", 80)
        ) ?: return
        val lines = rsp.optJSONArray("lines") ?: return
        for (i in 0 until lines.length()) {
            val line = lines.optJSONObject(i) ?: continue
            val seq = line.optLong("seq", 0L)
            if (seq > lastConsoleSeq) lastConsoleSeq = seq
            val level = when (line.optString("level", "INFO").uppercase(Locale.US)) {
                "ERROR" -> ConsoleLine.Level.ERROR
                "WARN" -> ConsoleLine.Level.WARN
                else -> ConsoleLine.Level.INFO
            }
            _console.tryEmit(
                ConsoleLine(
                    ts = nowTs(),
                    level = level,
                    tag = line.optString("tag", "USB"),
                    msg = line.optString("msg", "")
                )
            )
        }
    }

    private suspend fun pollPacketsOnceUsb() {
        val rsp = usbRpc(
            "packets",
            JSONObject()
                .put("since", lastPacketSeq)
                .put("limit", 150)
        ) ?: return
        val lines = rsp.optJSONArray("lines") ?: return
        for (i in 0 until lines.length()) {
            val line = lines.optJSONObject(i) ?: continue
            val seq = line.optLong("seq", 0L)
            if (seq > lastPacketSeq) lastPacketSeq = seq
            _packets.tryEmit(
                PacketLine(
                    seq = seq,
                    ms = line.optLong("ms", 0L),
                    type = line.optInt("type", -1),
                    subtype = line.optInt("subtype", -1),
                    len = line.optInt("len", 0),
                    rssi = line.optInt("rssi", -127),
                    channel = line.optInt("ch", 0),
                    src = line.optString("src", ""),
                    dst = line.optString("dst", ""),
                    bssid = line.optString("bssid", "")
                )
            )
        }
    }

    private suspend fun usbRpc(cmd: String, params: JSONObject = JSONObject(), timeoutMs: Int = 4000): JSONObject? {
        val port = usbPort ?: return null
        return usbRpcMutex.withLock {
            val reqId = usbRpcId++
            val req = JSONObject().apply {
                put("id", reqId)
                put("cmd", cmd)
                val names = params.keys()
                while (names.hasNext()) {
                    val k = names.next()
                    put(k, params.get(k))
                }
            }
            val line = req.toString() + "\n"
            try {
                port.write(line.toByteArray(Charsets.UTF_8), 1200)
            } catch (e: Exception) {
                logError("USB", "Write failed: ${e.message}")
                return@withLock null
            }

            val deadline = System.currentTimeMillis() + timeoutMs
            val tmp = ByteArray(512)
            while (System.currentTimeMillis() < deadline) {
                val parsed = drainUsbJsonLines(reqId)
                if (parsed != null) return@withLock parsed
                val n = try {
                    port.read(tmp, 180)
                } catch (_: Exception) {
                    0
                }
                if (n > 0) {
                    usbRxBuf.append(String(tmp, 0, n, Charsets.UTF_8))
                    val again = drainUsbJsonLines(reqId)
                    if (again != null) return@withLock again
                }
            }
            logError("USB", "RPC timeout for '$cmd'")
            null
        }
    }

    private fun drainUsbJsonLines(expectId: Int): JSONObject? {
        while (true) {
            val idx = usbRxBuf.indexOf("\n")
            if (idx < 0) return null
            val line = usbRxBuf.substring(0, idx).trim()
            usbRxBuf.delete(0, idx + 1)
            if (line.isBlank()) continue
            val obj = runCatching { JSONObject(line) }.getOrNull() ?: continue
            if (obj.optInt("id", -1) == expectId) return obj
        }
    }

    private fun decodeHex(hexRaw: String): ByteArray {
        val hex = hexRaw.trim()
        if (hex.isEmpty() || hex.length % 2 != 0) return ByteArray(0)
        val out = ByteArray(hex.length / 2)
        var i = 0
        while (i < hex.length) {
            val b = hex.substring(i, i + 2).toIntOrNull(16) ?: return ByteArray(0)
            out[i / 2] = b.toByte()
            i += 2
        }
        return out
    }

    // -------------------------------------------------------------------------
    // AI-Assisted Pentesting (Phase 2)
    // -------------------------------------------------------------------------

    override suspend fun fetchAiFrames(): TargetProfile? {
        if (transport == Transport.USB) {
            val rsp = usbRpc("ai_frames") ?: return null
            return parseAiFramesResponse(rsp.toString())
        }
        val ip = targetIp ?: return null
        return kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) {
            try {
                val request = Request.Builder().url(baseUrl("/api/ai/frames")).build()
                client.newCall(request).execute().use { response ->
                    if (!response.isSuccessful) return@withContext null
                    val body = response.body?.string() ?: return@withContext null
                    parseAiFramesResponse(body)
                }
            } catch (e: Exception) {
                logError("AI", "fetchAiFrames failed: ${e.message}")
                null
            }
        }
    }

    private fun parseAiFramesResponse(json: String): TargetProfile? {
        return try {
            val root    = JSONObject(json)
            if (!root.optBoolean("ok", false)) return null
            val tgtObj  = root.optJSONObject("target") ?: return null
            val ssid    = tgtObj.optString("ssid", "")
            val bssid   = tgtObj.optString("bssid", "")
            val apOui   = tgtObj.optString("oui",   bssid.take(8))
            val channel = tgtObj.optInt("channel", 0)
            val rssi    = tgtObj.optInt("rssi", -99)
            val auth    = tgtObj.optString("auth", "Unknown")

            val apVendor = OuiDatabase.resolve(apOui)

            // Parse handshake list — take the first valid one for the profile
            val hsArr = root.optJSONArray("handshakes") ?: return null
            var bestMask = 0
            var clientMac: String? = null
            var staOui: String? = null
            var staVendor: String? = null
            val frames = mutableListOf<EapolFrameInfo>()

            for (i in 0 until hsArr.length()) {
                val hs = hsArr.getJSONObject(i)
                val mask = hs.optInt("mask", 0)
                if (mask == 0) continue
                if (mask.countOneBits() <= bestMask.countOneBits()) continue

                bestMask  = mask
                clientMac = hs.optString("station").takeIf { it.isNotBlank() }
                staOui    = hs.optString("sta_oui").takeIf { it.isNotBlank() }
                staVendor = staOui?.let { OuiDatabase.resolve(it) }

                frames.clear()
                val frArr = hs.optJSONArray("frames") ?: continue
                for (j in 0 until frArr.length()) {
                    val fr = frArr.getJSONObject(j)
                    val msgNum    = fr.optInt("msg", j + 1)
                    val eapolHex  = fr.optString("eapol_hex", "")
                    val frameHex  = fr.optString("frame_hex", "")
                    val fRssi     = fr.optInt("rssi", -99)
                    val ts        = fr.optLong("ts", 0L)
                    FrameParser.parseEapol(msgNum, eapolHex, frameHex, fRssi, ts)
                        ?.let { frames.add(it) }
                }
            }

            if (bestMask == 0) return null

            TargetProfile(
                ssid          = ssid,
                bssid         = bssid,
                apOui         = apOui,
                apVendor      = apVendor,
                clientMac     = clientMac,
                staOui        = staOui,
                staVendor     = staVendor,
                channel       = channel,
                rssi          = rssi,
                auth          = auth,
                eapolMask     = bestMask,
                hasValidPair  = frames.any { it.hasMic && !it.hasAck } &&
                                frames.any { !it.hasMic &&  it.hasAck },
                frames        = frames
            )
        } catch (e: Exception) {
            logError("AI", "parseAiFramesResponse error: ${e.message}")
            null
        }
    }

    override suspend fun injectRaw(channel: Int, frameHex: String): Boolean {
        if (transport == Transport.USB) {
            val rsp = usbRpc(
                "ai_inject_raw",
                JSONObject().put("channel", channel).put("frame", frameHex)
            )
            return rsp?.optBoolean("ok", false) == true
        }
        val ip = targetIp ?: return false
        return kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) {
            var result = false
            InjectionDispatcher(ip).injectRaw(channel, frameHex) { ok, msg ->
                result = ok
                if (ok) logInfo("AI", msg) else logError("AI", msg)
            }
            result
        }
    }

    override suspend fun injectDeauth(
        bssid: String,
        client: String,
        reason: Int,
        count: Int,
        channel: Int
    ): Boolean {
        if (transport == Transport.USB) {
            val rsp = usbRpc(
                "ai_inject_deauth",
                JSONObject()
                    .put("bssid", bssid)
                    .put("client", client)
                    .put("reason", reason)
                    .put("count", count)
                    .put("channel", channel)
            )
            return rsp?.optBoolean("ok", false) == true
        }
        val ip = targetIp ?: return false
        return kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) {
            var result = false
            InjectionDispatcher(ip).injectDeauth(bssid, client, reason, count, channel) { ok, msg ->
                result = ok
                if (ok) logInfo("AI", msg) else logError("AI", msg)
            }
            result
        }
    }

    override suspend fun fetchInjectionTelemetry(): InjectionTelemetry? {
        if (transport == Transport.USB) {
            val obj = usbRpc("status") ?: return null
            val yoink = obj.optJSONObject("yoink")
            return InjectionTelemetry(
                packets = obj.optLong("packets", 0L),
                beacons = obj.optLong("beacons", 0L),
                handshakes = obj.optLong("handshakes", 0L),
                sniffActive = obj.optBoolean("sniffActive", false),
                lockChannel = obj.optBoolean("lockChannel", false),
                yoinkState = yoink?.optString("state"),
                yoinkTarget = yoink?.optString("target"),
                yoinkDeauths = yoink?.optLong("deauths"),
                yoinkHandshakes = yoink?.optLong("hs")
            )
        }
        if (targetIp == null) return null
        return kotlinx.coroutines.withContext(kotlinx.coroutines.Dispatchers.IO) {
            try {
                val request = Request.Builder().url(baseUrl("/api/status")).build()
                client.newCall(request).execute().use { response ->
                    if (!response.isSuccessful) return@withContext null
                    val body = response.body?.string() ?: return@withContext null
                    val obj = JSONObject(body)
                    val yoink = obj.optJSONObject("yoink")
                    InjectionTelemetry(
                        packets = obj.optLong("packets", 0L),
                        beacons = obj.optLong("beacons", 0L),
                        handshakes = obj.optLong("handshakes", 0L),
                        sniffActive = obj.optBoolean("sniffActive", false),
                        lockChannel = obj.optBoolean("lockChannel", false),
                        yoinkState = yoink?.optString("state"),
                        yoinkTarget = yoink?.optString("target"),
                        yoinkDeauths = yoink?.optLong("deauths"),
                        yoinkHandshakes = yoink?.optLong("hs")
                    )
                }
            } catch (e: Exception) {
                logError("AI", "fetchInjectionTelemetry failed: ${e.message}")
                null
            }
        }
    }
}
