/* Source: Generated by ChatGPT */
package com.example.cydcompanion.ui


import com.example.cydcompanion.data.CydRepository

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.example.cydcompanion.domain.SessionSummary
import kotlinx.coroutines.flow.collectLatest

@Composable
fun AnalyzeScreen(repo: CydRepository) {
    // Delegate to the new comprehensive DataScreen with WPA-SEC and PCAP analysis
    DataScreen(repo)
}
