/* Source: Generated by ChatGPT */
package com.example.cydcompanion.ui

import android.os.SystemClock
import androidx.compose.foundation.background
import androidx.compose.foundation.gestures.detectTapGestures
import androidx.compose.foundation.gestures.detectDragGestures
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.offset
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Analytics
import androidx.compose.material.icons.filled.Article
import androidx.compose.material.icons.filled.CloudUpload
import androidx.compose.material.icons.filled.Gamepad
import androidx.compose.material.icons.filled.PlayArrow
import androidx.compose.material.icons.filled.Psychology
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.NavigationBar
import androidx.compose.material3.NavigationBarItem
import androidx.compose.material3.NavigationBarItemDefaults
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableFloatStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.drawBehind
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.input.pointer.util.VelocityTracker
import androidx.compose.ui.layout.onSizeChanged
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalDensity
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.IntOffset
import androidx.compose.ui.unit.IntSize
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.currentBackStackEntryAsState
import androidx.navigation.compose.rememberNavController
import com.example.cydcompanion.data.WifiCydRepository
import com.example.cydcompanion.domain.ConnectionState
import com.example.cydcompanion.ui.background.HypercubeOverlay
import com.example.cydcompanion.ui.background.TokyoNeonBackdrop
import kotlin.math.abs

private sealed class Tab(val route: String, val label: String, val icon: @Composable (Boolean) -> Unit) {
    data object Live : Tab("live", "LIVE", { selected ->
        Icon(Icons.Filled.PlayArrow, contentDescription = null, tint = if (selected) MaterialTheme.colorScheme.primary else Color.Gray)
    })
    data object Analyze : Tab("analyze", "DATA", { selected ->
        Icon(Icons.Filled.Analytics, contentDescription = null, tint = if (selected) MaterialTheme.colorScheme.primary else Color.Gray)
    })
    data object Control : Tab("control", "REMOT", { selected ->
        Icon(Icons.Filled.Gamepad, contentDescription = null, tint = if (selected) MaterialTheme.colorScheme.primary else Color.Gray)
    })
    data object Export : Tab("export", "FILE", { selected ->
        Icon(Icons.Filled.CloudUpload, contentDescription = null, tint = if (selected) MaterialTheme.colorScheme.primary else Color.Gray)
    })
    data object Cli : Tab("cli", "CLI", { selected ->
        Icon(Icons.Filled.Article, contentDescription = null, tint = if (selected) MaterialTheme.colorScheme.primary else Color.Gray)
    })
    data object AiPentest : Tab("ai", "AI", { selected ->
        Icon(Icons.Filled.Psychology, contentDescription = null, tint = if (selected) MaterialTheme.colorScheme.primary else Color.Gray)
    })
}

@Composable
fun AppRoot() {
    val nav = rememberNavController()
    val context = LocalContext.current
    val repo = remember { WifiCydRepository(context) }
    val conn by repo.connection.collectAsState()
    val secretTapTimes = remember { ArrayDeque<Long>() }
    val tabs = listOf(Tab.Live, Tab.Analyze, Tab.Control, Tab.Export, Tab.Cli, Tab.AiPentest)

    val density = LocalDensity.current
    val cubeSizeDp = 108.dp
    val cubeSizePx = with(density) { cubeSizeDp.toPx() }
    val initialTopPx = with(density) { 18.dp.toPx() }
    val initialRightPx = with(density) { 12.dp.toPx() }

    var viewportSize by remember { mutableStateOf(IntSize.Zero) }
    var cubePlaced by remember { mutableStateOf(false) }
    var cubeX by remember { mutableFloatStateOf(0f) }
    var cubeY by remember { mutableFloatStateOf(0f) }
    var cubeVx by remember { mutableFloatStateOf(0f) }
    var cubeVy by remember { mutableFloatStateOf(0f) }

    LaunchedEffect(viewportSize, cubeSizePx) {
        if (!cubePlaced && viewportSize.width > 0 && viewportSize.height > 0) {
            cubeX = (viewportSize.width - cubeSizePx - initialRightPx).coerceAtLeast(0f)
            cubeY = initialTopPx
            cubePlaced = true
        }
    }

    LaunchedEffect(viewportSize, cubeSizePx, cubePlaced) {
        var lastMs = SystemClock.elapsedRealtime()
        while (true) {
            kotlinx.coroutines.delay(16)
            if (!cubePlaced || viewportSize.width <= 0 || viewportSize.height <= 0) continue

            val now = SystemClock.elapsedRealtime()
            val dt = ((now - lastMs).coerceAtLeast(1L)) / 1000f
            lastMs = now

            cubeX += cubeVx * dt
            cubeY += cubeVy * dt

            cubeVx *= 0.992f
            cubeVy *= 0.992f
            if (abs(cubeVx) < 7f) cubeVx = 0f
            if (abs(cubeVy) < 7f) cubeVy = 0f

            val maxX = (viewportSize.width - cubeSizePx).coerceAtLeast(0f)
            val maxY = (viewportSize.height - cubeSizePx).coerceAtLeast(0f)
            val bounce = 0.84f

            if (cubeX < 0f) {
                cubeX = 0f
                cubeVx = abs(cubeVx) * bounce
            } else if (cubeX > maxX) {
                cubeX = maxX
                cubeVx = -abs(cubeVx) * bounce
            }

            if (cubeY < 0f) {
                cubeY = 0f
                cubeVy = abs(cubeVy) * bounce
            } else if (cubeY > maxY) {
                cubeY = maxY
                cubeVy = -abs(cubeVy) * bounce
            }
        }
    }

    TokyoNeonBackdrop {
        Scaffold(
            containerColor = Color.Transparent,
            topBar = {
                ConnectionHeader(conn)
            },
            bottomBar = {
                Column {
                    Box(
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(1.dp)
                            .background(
                                Brush.horizontalGradient(
                                    listOf(Color.Transparent, MaterialTheme.colorScheme.primary, Color.Transparent)
                                )
                            )
                    )

                    NavigationBar(
                        containerColor = MaterialTheme.colorScheme.surface.copy(alpha = 0.9f),
                        tonalElevation = 0.dp,
                        modifier = Modifier.height(72.dp)
                    ) {
                        val current by nav.currentBackStackEntryAsState()
                        val route = current?.destination?.route

                        tabs.forEach { tab ->
                            val selected = route == tab.route
                            NavigationBarItem(
                                selected = selected,
                                onClick = {
                                    if (!selected) {
                                        nav.navigate(tab.route) {
                                            popUpTo(nav.graph.startDestinationId)
                                            launchSingleTop = true
                                        }
                                    }
                                },
                                icon = { tab.icon(selected) },
                                label = {
                                    Text(
                                        text = tab.label,
                                        style = MaterialTheme.typography.labelSmall.copy(
                                            fontWeight = if (selected) FontWeight.Black else FontWeight.Normal,
                                            letterSpacing = 1.sp,
                                            color = if (selected) MaterialTheme.colorScheme.primary else Color.Gray
                                        )
                                    )
                                },
                                colors = NavigationBarItemDefaults.colors(
                                    indicatorColor = MaterialTheme.colorScheme.primary.copy(alpha = 0.1f)
                                )
                            )
                        }
                    }
                }
            }
        ) { padding ->
            Box(
                modifier = Modifier
                    .fillMaxSize()
                    .padding(padding)
                    .onSizeChanged { viewportSize = it }
            ) {
                ViewportDecorations()

                NavHost(navController = nav, startDestination = Tab.Live.route) {
                    composable(Tab.Live.route) { LiveScreen(repo = repo) }
                    composable(Tab.Analyze.route) { AnalyzeScreen(repo = repo) }
                    composable(Tab.Control.route) { ControlScreen(repo = repo) }
                    composable(Tab.Export.route) { ExportScreen(repo = repo) }
                    composable(Tab.Cli.route) { CliHelpScreen(repo = repo) }
                    composable(Tab.AiPentest.route) { AiScreen(repo = repo) }
                    composable("secret_game") { EatTheRichGameScreen() }
                }

                Box(
                    modifier = Modifier
                        .offset { IntOffset(cubeX.toInt(), cubeY.toInt()) }
                        .size(cubeSizeDp)
                        .pointerInput(Unit) {
                            val tracker = VelocityTracker()
                            detectDragGestures(
                                onDragStart = {
                                    cubeVx = 0f
                                    cubeVy = 0f
                                    tracker.resetTracking()
                                }
                            ) { change, dragAmount ->
                                tracker.addPosition(change.uptimeMillis, change.position)
                                cubeX += dragAmount.x
                                cubeY += dragAmount.y
                                val vel = tracker.calculateVelocity()
                                cubeVx = vel.x
                                cubeVy = vel.y
                                change.consume()
                            }
                        }
                        .pointerInput(Unit) {
                            detectTapGestures(
                                onTap = {
                                    val now = SystemClock.elapsedRealtime()
                                    secretTapTimes.addLast(now)
                                    while (secretTapTimes.isNotEmpty() && now - secretTapTimes.first() > 5_000L) {
                                        secretTapTimes.removeFirst()
                                    }
                                    if (secretTapTimes.size >= 5) {
                                        secretTapTimes.clear()
                                        nav.navigate("secret_game") { launchSingleTop = true }
                                    }
                                }
                            )
                            }
                ) {
                    HypercubeOverlay(modifier = Modifier.fillMaxSize())
                }
            }
        }
    }
}

@Composable
fun ConnectionHeader(conn: ConnectionState) {
    val statusColor = when (conn.status) {
        ConnectionState.Status.CONNECTED -> MaterialTheme.colorScheme.secondary
        ConnectionState.Status.DISCONNECTED -> Color.Gray
        else -> MaterialTheme.colorScheme.primary
    }

    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(top = 8.dp, start = 16.dp, end = 16.dp),
        horizontalArrangement = Arrangement.SpaceBetween,
        verticalAlignment = Alignment.CenterVertically
    ) {
        Column {
            Text(
                text = "CYD_NODE: ${conn.deviceName ?: "OFFLINE"}",
                style = MaterialTheme.typography.labelMedium.copy(
                    color = Color.White.copy(alpha = 0.7f),
                    fontWeight = FontWeight.Bold
                )
            )
            Text(
                text = conn.status.name,
                style = MaterialTheme.typography.labelSmall.copy(
                    color = statusColor,
                    fontSize = 10.sp
                )
            )
        }

        Box(
            modifier = Modifier
                .size(8.dp)
                .background(statusColor, shape = androidx.compose.foundation.shape.CircleShape)
        )
    }
}

@Composable
fun ViewportDecorations() {
    Box(modifier = Modifier.fillMaxSize()) {
        Box(
            modifier = Modifier
                .align(Alignment.TopStart)
                .padding(8.dp)
                .size(20.dp)
                .drawBehind {
                    val stroke = 2.dp.toPx()
                    val s = this.size
                    drawLine(Color.White.copy(alpha = 0.2f), Offset(0f, 0f), Offset(s.width, 0f), stroke)
                    drawLine(Color.White.copy(alpha = 0.2f), Offset(0f, 0f), Offset(0f, s.height), stroke)
                }
        )
        Box(
            modifier = Modifier
                .align(Alignment.BottomEnd)
                .padding(8.dp)
                .size(20.dp)
                .drawBehind {
                    val stroke = 2.dp.toPx()
                    val s = this.size
                    drawLine(Color.White.copy(alpha = 0.2f), Offset(s.width, s.height), Offset(0f, s.height), stroke)
                    drawLine(Color.White.copy(alpha = 0.2f), Offset(s.width, s.height), Offset(s.width, 0f), stroke)
                }
        )
    }
}
