/* Source: Generated by ChatGPT */
package com.example.cydcompanion.ui

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.text.selection.SelectionContainer
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.produceState
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.cydcompanion.data.CydRepository
import org.json.JSONArray
import org.json.JSONObject
import java.util.Locale

@Composable
fun CliHelpScreen(repo: CydRepository) {
    val context = LocalContext.current
    val helpText by produceState("Loading CLI help...") {
        value = runCatching {
            context.assets.open("CLI-HELP.txt").bufferedReader().use { it.readText() }
        }.getOrElse { "Failed to load CLI-HELP.txt: ${it.message}" }
    }

    var cmdInput by remember { mutableStateOf("PING") }
    var paramsInput by remember { mutableStateOf("{}") }
    var statusText by remember { mutableStateOf("Ready") }

    ScreenScaffold(title = "CLI HELP") {
        NeonCard(header = "CUSTOM COMMAND") {
            Text(
                "Send raw control commands from app to firmware (active transport).",
                style = MaterialTheme.typography.bodySmall
            )
            Spacer(Modifier.height(10.dp))

            OutlinedTextField(
                value = cmdInput,
                onValueChange = { cmdInput = it },
                label = { Text("cmd") },
                singleLine = true,
                modifier = Modifier.fillMaxWidth()
            )

            Spacer(Modifier.height(8.dp))

            OutlinedTextField(
                value = paramsInput,
                onValueChange = { paramsInput = it },
                label = { Text("params JSON object") },
                modifier = Modifier
                    .fillMaxWidth()
                    .height(110.dp),
                textStyle = MaterialTheme.typography.bodySmall.copy(fontFamily = FontFamily.Monospace)
            )

            Spacer(Modifier.height(10.dp))

            Row(horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                NeonButton(
                    text = "SEND",
                    onClick = {
                        val cmd = cmdInput.trim().uppercase(Locale.US)
                        if (cmd.isEmpty()) {
                            statusText = "Error: cmd is empty."
                            return@NeonButton
                        }

                        val params = runCatching { parseParamsMap(paramsInput) }.getOrElse {
                            statusText = "Error: invalid JSON params (${it.message})"
                            return@NeonButton
                        }

                        repo.sendControlCommand(cmd, params)
                        statusText = "Sent: $cmd"
                    }
                )

                NeonButton(
                    text = "CLEAR",
                    onClick = {
                        cmdInput = ""
                        paramsInput = "{}"
                        statusText = "Cleared."
                    }
                )
            }

            Spacer(Modifier.height(8.dp))
            Text(
                statusText,
                style = MaterialTheme.typography.bodySmall.copy(color = MaterialTheme.colorScheme.secondary)
            )
        }

        Spacer(Modifier.height(14.dp))

        NeonCard(modifier = Modifier.weight(1f), header = "CLI-HELP.TXT") {
            val scroll = rememberScrollState()
            Column(
                modifier = Modifier
                    .fillMaxSize()
                    .verticalScroll(scroll)
            ) {
                SelectionContainer {
                    Text(
                        text = helpText,
                        fontFamily = FontFamily.Monospace,
                        fontSize = 12.sp,
                        lineHeight = 17.sp
                    )
                }
            }
        }
    }
}

private fun parseParamsMap(raw: String): Map<String, Any> {
    val text = raw.trim()
    if (text.isEmpty() || text == "{}") return emptyMap()

    val obj = JSONObject(text)
    val out = LinkedHashMap<String, Any>()
    val keys = obj.keys()
    while (keys.hasNext()) {
        val key = keys.next()
        val value = obj.get(key)
        out[key] = when (value) {
            JSONObject.NULL -> ""
            is String -> value
            is Boolean -> value
            is Int -> value
            is Long -> value
            is Double -> value
            is Float -> value.toDouble()
            is Number -> value.toDouble()
            is JSONObject -> value.toString()
            is JSONArray -> value.toString()
            else -> value.toString()
        }
    }
    return out
}
