/* Source: Generated by ChatGPT */
package com.example.cydcompanion.ui

import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.asImageBitmap
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.cydcompanion.data.CydRepository

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ControlScreen(repo: CydRepository) {
    val bitmap by repo.screenMirror.collectAsState()
    var brightness by remember { mutableFloatStateOf(0.85f) }
    var selectedMode by remember { mutableStateOf("NONE") }
    var deauthEnabled by remember { mutableStateOf(false) }
    var expanded by remember { mutableStateOf(false) }

    // Aligned with ESP32 automate modes + system WiFi modes
    val automateModes = listOf("NONE", "Y0INK", "RAW", "SCOPE", "JAMMIT")
    val wifiModes = listOf("WIFI_OFF", "WIFI_STA", "WIFI_AP", "WIFI_AP_STA")
    val allModes = automateModes + wifiModes

    ScreenScaffold(title = "CYD CONTROL") {
        // 1. Live View / Mirror
        NeonCard(header = "LIVE SYSTEM VIEW") {
            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .aspectRatio(320f / 240f)
                    .background(Color.Black)
                    .border(1.dp, MaterialTheme.colorScheme.primary.copy(alpha = 0.3f)),
                contentAlignment = Alignment.Center
            ) {
                bitmap?.let {
                    Image(
                        bitmap = it.asImageBitmap(),
                        contentDescription = "CYD Screen",
                        modifier = Modifier.fillMaxSize(),
                        contentScale = ContentScale.Fit
                    )
                } ?: Text(
                    "LINKING_STREAM...",
                    style = MaterialTheme.typography.labelMedium.copy(
                        color = MaterialTheme.colorScheme.primary.copy(alpha = 0.4f),
                        letterSpacing = 2.sp
                    )
                )
            }
        }

        Spacer(Modifier.height(16.dp))

        // 2. Automate & WiFi Mode Selection
        NeonCard(header = "AUTOMATION & RADIO") {
            Column(Modifier.fillMaxWidth()) {
                Text(
                    "Select Active Mode",
                    style = MaterialTheme.typography.labelMedium,
                    color = MaterialTheme.colorScheme.secondary
                )
                Spacer(Modifier.height(8.dp))

                ExposedDropdownMenuBox(
                    expanded = expanded,
                    onExpandedChange = { expanded = !expanded },
                    modifier = Modifier.fillMaxWidth()
                ) {
                    OutlinedTextField(
                        value = selectedMode,
                        onValueChange = {},
                        readOnly = true,
                        trailingIcon = { ExposedDropdownMenuDefaults.TrailingIcon(expanded = expanded) },
                        modifier = Modifier.menuAnchor().fillMaxWidth(),
                        colors = OutlinedTextFieldDefaults.colors(
                            focusedBorderColor = MaterialTheme.colorScheme.secondary,
                            unfocusedBorderColor = MaterialTheme.colorScheme.primary.copy(alpha = 0.4f),
                            focusedTextColor = Color.White,
                            unfocusedTextColor = Color.White
                        ),
                        textStyle = MaterialTheme.typography.bodyMedium.copy(fontWeight = FontWeight.Bold)
                    )

                    ExposedDropdownMenu(
                        expanded = expanded,
                        onDismissRequest = { expanded = false },
                        modifier = Modifier.background(MaterialTheme.colorScheme.surface)
                    ) {
                        allModes.forEach { m ->
                            DropdownMenuItem(
                                text = { 
                                    Text(
                                        text = m,
                                        style = MaterialTheme.typography.bodyMedium,
                                        color = if (automateModes.contains(m)) 
                                            MaterialTheme.colorScheme.primary else Color.White
                                    ) 
                                },
                                onClick = {
                                    selectedMode = m
                                    expanded = false
                                    // Send specific command based on type
                                    if (wifiModes.contains(m)) {
                                        repo.sendControlCommand("SET_WIFI", mapOf("mode" to m))
                                    } else {
                                        repo.sendControlCommand("SET_MODE", mapOf("mode" to m))
                                    }
                                }
                            )
                        }
                    }
                }

                Spacer(Modifier.height(16.dp))

                // Deauth Toggle (Critical for Y0INK/JAMMIT)
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Column {
                        Text("Active Injection", style = MaterialTheme.typography.bodyMedium)
                        Text(
                            "Force handshakes (Deauth)", 
                            style = MaterialTheme.typography.labelSmall,
                            color = MaterialTheme.colorScheme.error
                        )
                    }
                    Switch(
                        checked = deauthEnabled,
                        onCheckedChange = { 
                            deauthEnabled = it
                            repo.sendControlCommand("SET_CONFIG", mapOf("key" to "wifi_enableDeauth", "val" to it))
                        },
                        colors = SwitchDefaults.colors(
                            checkedThumbColor = MaterialTheme.colorScheme.error,
                            checkedTrackColor = MaterialTheme.colorScheme.error.copy(alpha = 0.4f)
                        )
                    )
                }
            }
        }

        Spacer(Modifier.height(16.dp))

        // 3. Hardware Controls
        NeonCard(header = "HARDWARE") {
            Column(Modifier.fillMaxWidth()) {
                Text("Backlight Intensity", style = MaterialTheme.typography.labelMedium)
                Slider(
                    value = brightness,
                    onValueChange = { 
                        brightness = it
                        repo.sendControlCommand("SET_BRIGHT", mapOf("val" to (it * 255).toInt()))
                    },
                    colors = SliderDefaults.colors(thumbColor = MaterialTheme.colorScheme.primary)
                )

                Spacer(Modifier.height(8.dp))
                
                Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                    NeonButton(text = "REBOOT", onClick = { repo.sendControlCommand("REBOOT") }, isDanger = true)
                    NeonButton(text = "PING", onClick = { repo.sendControlCommand("PING") })
                }
            }
        }
    }
}
