/* Source: Generated by ChatGPT */
package com.example.cydcompanion.ui

import android.net.Uri
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.InsertDriveFile
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.Download
import androidx.compose.material.icons.filled.Folder
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import com.example.cydcompanion.data.CydRepository
import com.example.cydcompanion.data.SettingsStore
import com.example.cydcompanion.data.VaultManager
import com.example.cydcompanion.domain.ConnectionState
import com.example.cydcompanion.domain.CydFile
import kotlinx.coroutines.launch
import androidx.compose.runtime.snapshotFlow
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.debounce
import kotlinx.coroutines.flow.distinctUntilChanged
import kotlinx.coroutines.withContext
import kotlin.math.roundToInt
import java.util.Locale

private val ALLOWED_CAPTURE_EXTENSIONS = setOf("pcap", "pcapng", "log", "txt")

private fun isAllowedCaptureFile(pathOrName: String): Boolean {
    val clean = pathOrName.substringAfterLast('/').substringAfterLast('\\')
    val ext = clean.substringAfterLast('.', "").lowercase(Locale.US)
    return ext in ALLOWED_CAPTURE_EXTENSIONS
}

@Composable
@OptIn(kotlinx.coroutines.FlowPreview::class)
fun ExportScreen(repo: CydRepository) {
    val context = LocalContext.current
    val settings = remember { SettingsStore(context) }
    val vault = remember { VaultManager(context) }
    val scope = rememberCoroutineScope()

    val connection by repo.connection.collectAsState()
    val files by repo.currentFiles.collectAsState()
    var currentPath by remember { mutableStateOf("/sd") }
    val atRoot = currentPath == "/" || currentPath == "/sd" || currentPath == "/lfs"

    val projectId by settings.vaultProjectId.collectAsState(initial = "default")
    val activeCaptureId by settings.vaultCaptureId.collectAsState(initial = null)
    val activeCaptureLabel by settings.vaultCaptureLabel.collectAsState(initial = null)

    var projectInput by remember { mutableStateOf(projectId) }
    LaunchedEffect(projectId) {
        projectInput = projectId
    }
    LaunchedEffect(Unit) {
        snapshotFlow { projectInput }
            .debounce(350)
            .distinctUntilChanged()
            .collect { settings.setVaultProjectId(it) }
    }

    var vaultStatus by remember { mutableStateOf("") }
    var isPulling by remember { mutableStateOf(false) }
    var pullProgress by remember { mutableStateOf("") }
    var pullFraction by remember { mutableStateOf(0f) }
    var currentFileExpectedBytes by remember { mutableStateOf(0L) }
    var totalExpectedBytes by remember { mutableStateOf(0L) }
    var transferredBytes by remember { mutableStateOf(0L) }
    var transferredFiles by remember { mutableStateOf(0) }
    var failedFiles by remember { mutableStateOf(0) }
    val transferLog = remember { mutableStateListOf<String>() }
    val transferLogListState = rememberLazyListState()
    var showBookmarkDialog by remember { mutableStateOf(false) }
    var bookmarkUrl by remember { mutableStateOf("") }
    var bookmarkTitle by remember { mutableStateOf("") }

    suspend fun getOrCreateCaptureId(source: String, label: String = source): String {
        val existing = activeCaptureId
        if (!existing.isNullOrBlank()) return existing

        val created = vault.createCapture(projectId = projectId, label = label, source = source)
        settings.setVaultCaptureId(created.captureId)
        settings.setVaultCaptureLabel(created.label)
        val capPath = vault.getCapturePath(projectId, created.captureId).absolutePath
        vaultStatus = "✓ Active capture: ${created.label}\n$capPath"
        return created.captureId
    }

    val importFolderLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.OpenDocumentTree()
    ) { uri: Uri? ->
        if (uri == null) return@rememberLauncherForActivityResult
        scope.launch {
            val capId = getOrCreateCaptureId(source = "PHONE_SD", label = "PHONE_SD")
            try {
                // Persist permission so the user doesn't need to re-consent each time for this tree.
                context.contentResolver.takePersistableUriPermission(
                    uri,
                    android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION
                )
            } catch (_: Exception) {
                // Best-effort; some providers do not allow persistable permissions.
            }
            val count = vault.importDocumentTree(projectId, capId, uri)
            val capPath = vault.getCapturePath(projectId, capId).absolutePath
            vaultStatus = "✓ Imported folder into vault ($count allowed file(s): .pcap .pcapng .log .txt)\n$capPath"
        }
    }

    val importMediaLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.OpenMultipleDocuments()
    ) { uris: List<Uri> ->
        if (uris.isEmpty()) return@rememberLauncherForActivityResult
        scope.launch {
            val capId = getOrCreateCaptureId(source = "PHONE_MEDIA", label = "PHONE_MEDIA")
            val out = vault.importUris(projectId, capId, uris)
            val skipped = (uris.size - out.size).coerceAtLeast(0)
            val capPath = vault.getCapturePath(projectId, capId).absolutePath
            vaultStatus = "✓ Imported ${out.size} allowed file(s) into vault" +
                if (skipped > 0) "\nSkipped $skipped unsupported file(s)" else "" +
                "\n$capPath"
        }
    }

    suspend fun pullCurrentFolderToVault(recursive: Boolean = false) {
        if (isPulling) return
        
        // Check connection first
        if (connection.status != ConnectionState.Status.CONNECTED) {
            vaultStatus = "✗ CYD not connected. Go to LIVE tab first."
            return
        }
        
        isPulling = true
        pullProgress = "Initializing..."
        pullFraction = 0f
        currentFileExpectedBytes = 0L
        totalExpectedBytes = 0L
        transferredBytes = 0L
        transferredFiles = 0
        failedFiles = 0
        transferLog.clear()
        vaultStatus = "⟳ Starting pull from CYD..."
        
        try {
            val cap = getOrCreateCaptureId(source = "CYD:${currentPath}", label = currentPath)
            
            val allFiles = if (recursive) {
                // Use recursive listing to get all files including subfolders
                repo.listFilesRecursive(currentPath).filter { !it.isDirectory }
            } else {
                files.filter { !it.isDirectory }
            }
            val filesToPull = allFiles.filter { isAllowedCaptureFile(it.path.ifBlank { it.name }) }
            val skippedByType = allFiles.size - filesToPull.size
            
            if (filesToPull.isEmpty()) {
                vaultStatus = if (allFiles.isEmpty()) {
                    "⚠ No files found in $currentPath (or list API returned none)"
                } else {
                    "⚠ No allowed files in $currentPath. Allowed: .pcap .pcapng .log .txt"
                }
                isPulling = false
                pullProgress = ""
                pullFraction = 0f
                return
            }

            var ok = 0
            val total = filesToPull.size
            totalExpectedBytes = filesToPull.sumOf { it.size.coerceAtLeast(0L) }
            val basePath = currentPath.trimEnd('/')
            val startMs = System.currentTimeMillis()
            vaultStatus = "⟳ Found $total allowed file(s), downloading..." +
                if (skippedByType > 0) " (skipped $skippedByType unsupported)" else ""

            // Tell the CYD to show a visual indicator while we pull from SD.
            runCatching { repo.setCompanionSync(true) }
            
            for ((idx, f) in filesToPull.withIndex()) {
                // Extract relative subPath
                val relativePath = f.path.removePrefix(basePath).trimStart('/')
                val subPath = relativePath.substringBeforeLast('/', "")
                val displayName = if (subPath.isNotEmpty()) "$subPath/${f.name}" else f.name
                currentFileExpectedBytes = f.size.coerceAtLeast(0L)
                
                pullProgress = "Downloading ${idx + 1}/$total: $displayName"
                pullFraction = if (totalExpectedBytes > 0L) {
                    (transferredBytes.toFloat() / totalExpectedBytes.toFloat()).coerceIn(0f, 1f)
                } else {
                    (idx.toFloat() / total.toFloat()).coerceIn(0f, 1f)
                }
                val bytes = withContext(Dispatchers.IO) { repo.downloadFileBytes(f) }
                if (bytes == null) {
                    failedFiles++
                    transferLog.add("✗ ${idx + 1}/$total  $displayName")
                    pullProgress = "Failed: $displayName"
                    kotlinx.coroutines.delay(800)
                    continue
                }
                withContext(Dispatchers.IO) {
                    vault.saveBytes(projectId, cap, f.name, bytes, subPath = subPath)
                }
                ok++
                transferredFiles = ok
                transferredBytes += bytes.size.toLong()
                pullFraction = if (totalExpectedBytes > 0L) {
                    (transferredBytes.toFloat() / totalExpectedBytes.toFloat()).coerceIn(0f, 1f)
                } else {
                    ((idx + 1).toFloat() / total.toFloat()).coerceIn(0f, 1f)
                }
                transferLog.add("✓ ${idx + 1}/$total  $displayName  (${formatBytes(bytes.size.toLong())})")
                if (transferLog.size > 120) {
                    transferLog.removeRange(0, transferLog.size - 120)
                }
            }
            currentFileExpectedBytes = 0L
            pullFraction = 1f
            val elapsed = (System.currentTimeMillis() - startMs).coerceAtLeast(1L)
            val speed = (transferredBytes.toDouble() / (elapsed / 1000.0)).toLong()
            val capPath = vault.getCapturePath(projectId, cap).absolutePath
            vaultStatus = "✓ Pulled $ok/$total allowed file(s) in ${elapsed / 1000.0}s\n${formatBytes(transferredBytes)} total" +
                "\nAvg speed ${formatBytes(speed)}/s" +
                if (skippedByType > 0) "\nSkipped $skippedByType unsupported file(s)\n$capPath" else "\n$capPath"
            pullProgress = ""
        } catch (e: Exception) {
            vaultStatus = "✗ Pull failed: ${e.message}"
            pullProgress = ""
            pullFraction = 0f
            currentFileExpectedBytes = 0L
            totalExpectedBytes = 0L
        } finally {
            runCatching { repo.setCompanionSync(false) }
            isPulling = false
        }
    }

    LaunchedEffect(currentPath) {
        repo.listFiles(currentPath)
    }

    if (showBookmarkDialog) {
        AlertDialog(
            onDismissRequest = { showBookmarkDialog = false },
            title = { Text("Add Bookmark to Vault") },
            text = {
                Column(Modifier.fillMaxWidth(), verticalArrangement = Arrangement.spacedBy(10.dp)) {
                    OutlinedTextField(
                        value = bookmarkUrl,
                        onValueChange = { bookmarkUrl = it },
                        label = { Text("URL") },
                        modifier = Modifier.fillMaxWidth(),
                        singleLine = true
                    )
                    OutlinedTextField(
                        value = bookmarkTitle,
                        onValueChange = { bookmarkTitle = it },
                        label = { Text("Title (optional)") },
                        modifier = Modifier.fillMaxWidth(),
                        singleLine = true
                    )
                }
            },
            confirmButton = {
                TextButton(
                    onClick = {
                        val url = bookmarkUrl.trim()
                        if (url.isBlank()) return@TextButton
                        scope.launch {
                            val capId = getOrCreateCaptureId(source = "BOOKMARK", label = "BOOKMARK")
                            vault.addBookmark(projectId, capId, url = url, title = bookmarkTitle)
                            vaultStatus = "✓ Bookmark added to vault"
                            bookmarkUrl = ""
                            bookmarkTitle = ""
                            showBookmarkDialog = false
                        }
                    }
                ) { Text("ADD") }
            },
            dismissButton = {
                TextButton(onClick = { showBookmarkDialog = false }) { Text("CANCEL") }
            }
        )
    }

    ScreenScaffold(title = "SD EXPLORER") {
        NeonCard(header = currentPath) {
            Column(Modifier.fillMaxSize()) {

                // Connection status
                if (connection.status != ConnectionState.Status.CONNECTED) {
                    Row(
                        modifier = Modifier
                            .fillMaxWidth()
                            .background(MaterialTheme.colorScheme.error.copy(alpha = 0.15f), androidx.compose.foundation.shape.RoundedCornerShape(6.dp))
                            .padding(12.dp),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Icon(
                            Icons.Default.Refresh,
                            contentDescription = null,
                            tint = MaterialTheme.colorScheme.error,
                            modifier = Modifier.size(20.dp)
                        )
                        Spacer(Modifier.width(8.dp))
                        Text(
                            "CYD not connected. Go to LIVE tab to connect via WiFi.",
                            color = MaterialTheme.colorScheme.error,
                            style = MaterialTheme.typography.bodySmall
                        )
                    }
                    Spacer(Modifier.height(12.dp))
                }

                // Vault controls (local)
                Column(Modifier.fillMaxWidth()) {
                    Text(
                        text = "VAULT: ${activeCaptureLabel ?: "(no active capture)"}",
                        style = MaterialTheme.typography.labelMedium,
                        color = MaterialTheme.colorScheme.secondary
                    )
                    if (!activeCaptureId.isNullOrBlank()) {
                        Spacer(Modifier.height(4.dp))
                        Text(
                            text = "Path: ${vault.getCapturePath(projectId, activeCaptureId!!).absolutePath}",
                            style = MaterialTheme.typography.bodySmall,
                            color = Color.Gray
                        )
                    }
                    Spacer(Modifier.height(6.dp))
                    OutlinedTextField(
                        value = projectInput,
                        onValueChange = { projectInput = it },
                        label = { Text("Project") },
                        singleLine = true,
                        modifier = Modifier.fillMaxWidth()
                    )
                    
                    // Status feedback box
                    if (vaultStatus.isNotBlank() || isPulling) {
                        Spacer(Modifier.height(8.dp))
                        Box(
                            modifier = Modifier
                                .fillMaxWidth()
                                .background(
                                    if (vaultStatus.startsWith("✓")) Color(0xFF00FF41).copy(alpha = 0.1f)
                                    else if (vaultStatus.startsWith("✗")) MaterialTheme.colorScheme.error.copy(alpha = 0.1f)
                                    else MaterialTheme.colorScheme.secondary.copy(alpha = 0.1f),
                                    androidx.compose.foundation.shape.RoundedCornerShape(6.dp)
                                )
                                .border(
                                    1.dp,
                                    if (vaultStatus.startsWith("✓")) Color(0xFF00FF41).copy(alpha = 0.3f)
                                    else if (vaultStatus.startsWith("✗")) MaterialTheme.colorScheme.error.copy(alpha = 0.3f)
                                    else MaterialTheme.colorScheme.secondary.copy(alpha = 0.3f),
                                    androidx.compose.foundation.shape.RoundedCornerShape(6.dp)
                                )
                                .padding(12.dp)
                        ) {
                            Column {
                                if (vaultStatus.isNotBlank()) {
                                    Text(
                                        vaultStatus,
                                        style = MaterialTheme.typography.bodyMedium,
                                        fontWeight = FontWeight.SemiBold,
                                        color = if (vaultStatus.startsWith("✓")) Color(0xFF00FF41)
                                               else if (vaultStatus.startsWith("✗")) MaterialTheme.colorScheme.error
                                               else MaterialTheme.colorScheme.secondary
                                    )
                                }
                                if (isPulling && pullProgress.isNotBlank()) {
                                    Spacer(Modifier.height(6.dp))
                                    LinearProgressIndicator(
                                        progress = { pullFraction },
                                        modifier = Modifier.fillMaxWidth(),
                                        color = MaterialTheme.colorScheme.secondary,
                                        trackColor = MaterialTheme.colorScheme.secondary.copy(alpha = 0.2f)
                                    )
                                    Spacer(Modifier.height(6.dp))
                                    if (currentFileExpectedBytes > 0L) {
                                        Text(
                                            text = "Current file: ${formatBytes(currentFileExpectedBytes)}",
                                            style = MaterialTheme.typography.bodySmall,
                                            color = Color.Gray
                                        )
                                        Spacer(Modifier.height(4.dp))
                                    }
                                    LinearProgressIndicator(
                                        modifier = Modifier.fillMaxWidth(),
                                        color = MaterialTheme.colorScheme.primary,
                                        trackColor = MaterialTheme.colorScheme.primary.copy(alpha = 0.2f)
                                    )
                                    Spacer(Modifier.height(6.dp))
                                    if (totalExpectedBytes > 0L) {
                                        Text(
                                            text = "Overall: ${formatBytes(transferredBytes)} / ${formatBytes(totalExpectedBytes)}",
                                            style = MaterialTheme.typography.bodySmall,
                                            color = Color.Gray
                                        )
                                        Spacer(Modifier.height(6.dp))
                                    }
                                    Row(verticalAlignment = Alignment.CenterVertically) {
                                        CircularProgressIndicator(
                                            modifier = Modifier.size(16.dp),
                                            strokeWidth = 2.dp,
                                            color = MaterialTheme.colorScheme.secondary
                                        )
                                        Spacer(Modifier.width(8.dp))
                                        Text(
                                            pullProgress,
                                            style = MaterialTheme.typography.bodySmall,
                                            color = MaterialTheme.colorScheme.secondary
                                        )
                                    }
                                }
                            }
                        }
                    }
                    Spacer(Modifier.height(8.dp))
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp), modifier = Modifier.fillMaxWidth()) {
                        OutlinedButton(
                            onClick = {
                                scope.launch {
                                    getOrCreateCaptureId(source = "CYD:${currentPath}", label = currentPath)
                                }
                            },
                            modifier = Modifier.weight(1f)
                        ) {
                            Icon(Icons.Filled.Add, contentDescription = null)
                            Spacer(Modifier.width(6.dp))
                            Text("NEW CAPTURE")
                        }
                        OutlinedButton(
                            onClick = { scope.launch { pullCurrentFolderToVault(recursive = true) } },
                            enabled = !isPulling,
                            modifier = Modifier.weight(1f)
                        ) {
                            Icon(Icons.Filled.Download, contentDescription = null)
                            Spacer(Modifier.width(4.dp))
                            Text("PULL FROM CYD")
                        }
                    }
                    if (isPulling || transferLog.isNotEmpty()) {
                        Spacer(Modifier.height(8.dp))
                        Text(
                            text = "TRANSFER LOG  •  ok:$transferredFiles  fail:$failedFiles  bytes:${formatBytes(transferredBytes)}",
                            style = MaterialTheme.typography.labelSmall,
                            color = MaterialTheme.colorScheme.secondary
                        )
                        Spacer(Modifier.height(6.dp))
                        Box(
                            modifier = Modifier
                                .fillMaxWidth()
                                .heightIn(min = 80.dp, max = 160.dp)
                                .background(Color.Black.copy(alpha = 0.15f), RoundedCornerShape(6.dp))
                                .border(1.dp, Color.Gray.copy(alpha = 0.25f), RoundedCornerShape(6.dp))
                                .padding(8.dp)
                        ) {
                            LazyColumn(state = transferLogListState, modifier = Modifier.fillMaxSize()) {
                                items(transferLog) { line ->
                                    Text(
                                        text = line,
                                        style = MaterialTheme.typography.bodySmall,
                                        color = if (line.startsWith("✓")) Color(0xFF00FF41) else MaterialTheme.colorScheme.error
                                    )
                                }
                            }
                        }
                        LaunchedEffect(transferLog.size) {
                            if (transferLog.isNotEmpty()) {
                                transferLogListState.animateScrollToItem(transferLog.lastIndex)
                            }
                        }
                    }
                    Spacer(Modifier.height(8.dp))
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp), modifier = Modifier.fillMaxWidth()) {
                        OutlinedButton(
                            onClick = { importFolderLauncher.launch(null) },
                            enabled = !isPulling,
                            modifier = Modifier.weight(1f)
                        ) { Text("IMPORT FROM PHONE") }
                        OutlinedButton(
                            onClick = { importMediaLauncher.launch(arrayOf("*/*")) },
                            modifier = Modifier.weight(1f)
                        ) { Text("ADD FILES") }
                    }
                    Spacer(Modifier.height(8.dp))
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp), modifier = Modifier.fillMaxWidth()) {
                        OutlinedButton(
                            onClick = { showBookmarkDialog = true },
                            modifier = Modifier.weight(1f)
                        ) { Text("ADD BOOKMARK") }
                        OutlinedButton(
                            onClick = {
                                scope.launch {
                                    settings.setVaultCaptureId(null)
                                    settings.setVaultCaptureLabel(null)
                                    vaultStatus = "(Active capture cleared)"
                                    transferLog.clear()
                                }
                            },
                            modifier = Modifier.weight(1f)
                        ) { Text("CLEAR") }
                    }
                }

                Spacer(Modifier.height(10.dp))

                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.End,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    OutlinedButton(
                        onClick = {
                            currentPath = when {
                                currentPath.startsWith("/sd/") ->
                                    currentPath.substringBeforeLast("/").ifBlank { "/sd" }
                                currentPath.startsWith("/lfs/") ->
                                    currentPath.substringBeforeLast("/").ifBlank { "/lfs" }
                                else ->
                                    currentPath.substringBeforeLast("/").ifBlank { "/" }
                            }
                        },
                        enabled = !atRoot
                    ) {
                        Text("BACK")
                    }
                    Spacer(Modifier.width(8.dp))
                    IconButton(onClick = { repo.listFiles(currentPath) }) {
                        Icon(Icons.Filled.Refresh, contentDescription = "Refresh")
                    }
                }

                LazyColumn(modifier = Modifier.weight(1f)) {
                    if (files.isEmpty() && connection.status == ConnectionState.Status.CONNECTED) {
                        item {
                            Column(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .padding(24.dp),
                                horizontalAlignment = Alignment.CenterHorizontally
                            ) {
                                Text(
                                    "This folder is empty",
                                    style = MaterialTheme.typography.bodyMedium,
                                    color = Color.Gray
                                )
                                Spacer(Modifier.height(8.dp))
                                Text(
                                    "Navigate to a folder with files or check the CYD SD card",
                                    style = MaterialTheme.typography.bodySmall,
                                    color = Color.Gray
                                )
                            }
                        }
                    }
                    items(files) { file ->
                        FileItem(
                            file = file,
                            onFolderClick = { currentPath = it.path },
                            onDownloadClick = { repo.downloadFile(it) }
                        )
                        HorizontalDivider(color = Color.Gray.copy(alpha = 0.2f))
                    }
                }
            }
        }
    }
}

private fun formatBytes(bytes: Long): String {
    if (bytes < 1024) return "$bytes B"
    val kb = bytes / 1024.0
    if (kb < 1024) return "${(kb * 10.0).roundToInt() / 10.0} KB"
    val mb = kb / 1024.0
    if (mb < 1024) return "${(mb * 10.0).roundToInt() / 10.0} MB"
    val gb = mb / 1024.0
    return "${(gb * 10.0).roundToInt() / 10.0} GB"
}

@Composable
fun FileItem(file: CydFile, onFolderClick: (CydFile) -> Unit, onDownloadClick: (CydFile) -> Unit) {
    ListItem(
        modifier = Modifier.clickable { if (file.isDirectory) onFolderClick(file) },
        headlineContent = { Text(file.name) },
        supportingContent = {
            if (!file.isDirectory) {
                Text("${file.size} bytes")
            }
        },
        leadingContent = {
            Icon(
                if (file.isDirectory) Icons.Default.Folder else Icons.AutoMirrored.Filled.InsertDriveFile,
                contentDescription = null,
                tint = if (file.isDirectory) MaterialTheme.colorScheme.primary else Color.Gray
            )
        },
        trailingContent = {
            if (!file.isDirectory) {
                IconButton(onClick = { onDownloadClick(file) }) {
                    Icon(Icons.Default.Download, contentDescription = "Download", tint = MaterialTheme.colorScheme.secondary)
                }
            }
        },
        colors = ListItemDefaults.colors(containerColor = Color.Transparent)
    )
}
