/* Source: Generated by ChatGPT */
package com.example.cydcompanion.ui

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.cydcompanion.data.CydRepository
import com.example.cydcompanion.data.SettingsStore
import com.example.cydcompanion.domain.ConnectionState
import com.example.cydcompanion.domain.ConsoleLine
import com.example.cydcompanion.domain.PacketLine
import kotlinx.coroutines.launch
import kotlinx.coroutines.flow.collectLatest

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun LiveScreen(repo: CydRepository) {
    val context = LocalContext.current
    val settings = remember { SettingsStore(context) }
    val scope = rememberCoroutineScope()

    val conn by repo.connection.collectAsState()

    val lines = remember { mutableStateListOf<ConsoleLine>() }
    val packets = remember { mutableStateListOf<PacketLine>() }
    val listState = rememberLazyListState()
    
    var showWifiDialog by remember { mutableStateOf(false) }
    var ipInput by remember { mutableStateOf("192.168.4.1") }
    var showPackets by remember { mutableStateOf(true) }

    val savedIp by settings.cydIp.collectAsState(initial = "192.168.4.1")
    LaunchedEffect(savedIp) {
        // Keep the default IP in sync with persisted settings.
        // Don't clobber user edits while the dialog is open.
        if (!showWifiDialog) ipInput = savedIp
    }

    LaunchedEffect(Unit) {
        repo.console.collectLatest {
            if (lines.size > 200) lines.removeRange(0, 50)
            lines.add(it)
            if (!showPackets && lines.isNotEmpty()) {
                listState.animateScrollToItem(lines.size - 1)
            }
        }
    }

    LaunchedEffect(Unit) {
        repo.packets.collectLatest {
            if (packets.size > 500) packets.removeRange(0, 120)
            packets.add(it)
            if (showPackets && packets.isNotEmpty()) {
                listState.animateScrollToItem(packets.size - 1)
            }
        }
    }

    if (showWifiDialog) {
        AlertDialog(
            onDismissRequest = { showWifiDialog = false },
            title = { Text("Connect via WiFi") },
            text = {
                OutlinedTextField(
                    value = ipInput,
                    onValueChange = { ipInput = it },
                    label = { Text("CYD IP Address") },
                    modifier = Modifier.fillMaxWidth(),
                    singleLine = true
                )
            },
            confirmButton = {
                TextButton(onClick = {
                    scope.launch { settings.setCydIp(ipInput) }
                    repo.connectWifi(ipInput)
                    showWifiDialog = false
                }) {
                    Text("CONNECT")
                }
            },
            dismissButton = {
                TextButton(onClick = { showWifiDialog = false }) {
                    Text("CANCEL")
                }
            }
        )
    }

    ScreenScaffold(title = "System Link") {
        NeonCard(header = "CYD Node Status") {
            Column(Modifier.fillMaxWidth()) {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    val statusText = when (conn.status) {
                        ConnectionState.Status.DISCONNECTED -> "OFFLINE"
                        ConnectionState.Status.SCANNING -> "SCANNING"
                        ConnectionState.Status.CONNECTING -> "LINKING"
                        ConnectionState.Status.CONNECTED -> "STABLE"
                    }
                    
                    Text(
                        text = statusText,
                        style = MaterialTheme.typography.headlineSmall.copy(
                            fontWeight = FontWeight.ExtraBold,
                            color = if (conn.status == ConnectionState.Status.CONNECTED) 
                                MaterialTheme.colorScheme.secondary else MaterialTheme.colorScheme.error
                        )
                    )

                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        StatChip("RSSI", conn.rssi?.toString() ?: "---")
                        StatChip("MTU", conn.mtu?.toString() ?: "---")
                    }
                }

                Spacer(Modifier.height(8.dp))
                
                Text(
                    text = "DEVICE: ${conn.deviceName ?: "UNKNOWN_ID"}",
                    style = MaterialTheme.typography.bodySmall.copy(color = MaterialTheme.colorScheme.primary.copy(alpha = 0.6f))
                )

                Spacer(Modifier.height(16.dp))

                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    NeonButton(
                        text = "WiFi Link", 
                        onClick = { showWifiDialog = true },
                        enabled = conn.status == ConnectionState.Status.DISCONNECTED,
                        modifier = Modifier.weight(1f)
                    )
                    NeonButton(
                        text = "USB Link",
                        onClick = { repo.connectUsb() },
                        enabled = conn.status == ConnectionState.Status.DISCONNECTED,
                        modifier = Modifier.weight(1f)
                    )
                    NeonButton(
                        text = "Disconnect", 
                        onClick = { repo.disconnect() }, 
                        isDanger = true,
                        enabled = conn.status != ConnectionState.Status.DISCONNECTED,
                        modifier = Modifier.weight(1f)
                    )
                }
            }
        }

        Spacer(Modifier.height(16.dp))

        NeonCard(header = if (showPackets) "Packet Stream (Wireshark View)" else "Console Stream", modifier = Modifier.weight(1f)) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                NeonButton(
                    text = "Packets",
                    onClick = { showPackets = true },
                    enabled = !showPackets,
                    modifier = Modifier.weight(1f)
                )
                NeonButton(
                    text = "Console",
                    onClick = { showPackets = false },
                    enabled = showPackets,
                    modifier = Modifier.weight(1f)
                )
            }
            Spacer(Modifier.height(8.dp))

            if (showPackets) {
                Text(
                    text = "No   Ch RSSI Type/Sub  Source -> Dest            Len",
                    style = MaterialTheme.typography.bodySmall.copy(
                        color = MaterialTheme.colorScheme.primary.copy(alpha = 0.65f),
                        fontSize = 10.sp,
                        fontWeight = FontWeight.Bold
                    )
                )
            }

            LazyColumn(
                state = listState,
                modifier = Modifier.fillMaxSize(),
                contentPadding = PaddingValues(vertical = 4.dp)
            ) {
                if (showPackets) {
                    itemsIndexed(packets) { _, p ->
                        val typeName = when (p.type) {
                            0 -> "MGMT"
                            1 -> "CTRL"
                            2 -> "DATA"
                            else -> "UNK"
                        }
                        val row = String.format(
                            "%-4d %-2d %-4d %-4s/%-2d %-17s -> %-17s %4d",
                            p.seq, p.channel, p.rssi, typeName, p.subtype, p.src, p.dst, p.len
                        )
                        Text(
                            text = row,
                            style = MaterialTheme.typography.bodySmall.copy(
                                color = if (p.type == 2) Color.White else MaterialTheme.colorScheme.secondary,
                                fontSize = 10.sp
                            )
                        )
                    }
                } else {
                    itemsIndexed(lines) { _, line ->
                        Row(modifier = Modifier.padding(vertical = 2.dp)) {
                            Text(
                                text = "[${line.ts}]",
                                style = MaterialTheme.typography.bodySmall.copy(
                                    color = MaterialTheme.colorScheme.primary.copy(alpha = 0.5f),
                                    fontSize = 10.sp
                                )
                            )
                            Spacer(Modifier.width(6.dp))
                            Text(
                                text = "${line.tag} >",
                                style = MaterialTheme.typography.bodySmall.copy(
                                    color = MaterialTheme.colorScheme.secondary,
                                    fontWeight = FontWeight.Bold,
                                    fontSize = 11.sp
                                )
                            )
                            Spacer(Modifier.width(6.dp))
                            Text(
                                text = line.msg,
                                style = MaterialTheme.typography.bodySmall.copy(
                                    color = when(line.level) {
                                        ConsoleLine.Level.ERROR -> MaterialTheme.colorScheme.error
                                        ConsoleLine.Level.WARN -> MaterialTheme.colorScheme.secondary
                                        else -> Color.White
                                    },
                                    fontSize = 11.sp
                                )
                            )
                        }
                    }
                }
            }
        }
        
        Spacer(Modifier.height(8.dp))
        
        NeonCard {
            Text(
                "WIFI_LINK_ACTIVE_",
                style = MaterialTheme.typography.bodySmall.copy(color = MaterialTheme.colorScheme.secondary)
            )
        }
    }
}
