/* Source: Generated by ChatGPT */
package com.example.cydcompanion

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import com.example.cydcompanion.ui.AppRoot
import com.example.cydcompanion.ui.theme.TokyoNeonTheme

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            TokyoNeonTheme {
                AppRoot()
            }
        }
    }
}

