// Source: Generated by ChatGPT
import org.gradle.api.tasks.Copy

plugins {
    id("com.android.application") version "9.0.1"
    id("org.jetbrains.kotlin.android") version "2.2.10"
    id("org.jetbrains.kotlin.plugin.compose") version "2.2.10"
}

android {
    namespace = "com.example.cydcompanion"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.example.cydcompanion"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "0.1.0"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = "17" }

    buildFeatures { compose = true }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

dependencies {
    val composeBom = platform("androidx.compose:compose-bom:2024.06.00")
    implementation(composeBom)
    androidTestImplementation(composeBom)

    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.4")
    implementation("androidx.activity:activity-compose:1.9.1")

    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-tooling-preview")
    debugImplementation("androidx.compose.ui:ui-tooling")

    implementation("androidx.compose.material3:material3:1.2.1")
    implementation("androidx.compose.material:material-icons-extended")

    implementation("androidx.navigation:navigation-compose:2.7.7")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1")

    // Persistent app settings
    implementation("androidx.datastore:datastore-preferences:1.1.1")

    // Storage Access Framework helpers (importing folders/files from phone/SD)
    implementation("androidx.documentfile:documentfile:1.0.1")
    
    // WiFi Direct (HTTP)
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    // USB CDC/Serial host communication (phone -> CYD over OTG USB-C)
    implementation("com.github.mik3y:usb-serial-for-android:3.8.1")

    testImplementation("junit:junit:4.13.2")
}

val copyDebugApkAsCydCompanion by tasks.registering(Copy::class) {
    val debugApk = layout.buildDirectory.file("outputs/apk/debug/app-debug.apk")
    from(debugApk)
    into(layout.projectDirectory.dir("dist"))
    rename("app-debug.apk", "CYDCompanion.apk")
}

tasks.configureEach {
    if (name == "assembleDebug" || name == "packageDebug") {
        finalizedBy(copyDebugApkAsCydCompanion)
    }
}
