// Source: Generated by ChatGPT
// TFT_eSPI User Setup for ESP32 "Cheap Yellow Display" (CYD) clones
// LOCKED HARDWARE BASELINE (DO NOT CHANGE):
// - TFT: ILI9341 clone that REQUIRES ILI9341_2_DRIVER init sequence
// - Shared SPI: SCLK=14, MOSI=13, MISO=12
// - TFT_CS=15, TFT_DC=2, TFT_RST=-1
// - Touch uses XPT2046 on same SPI bus, CS=33 (handled in code via TOUCH_CS)

// IMPORTANT: Do NOT define TFT_WIDTH/TFT_HEIGHT here (runtime dims only).

#ifndef USER_SETUP_H
#define USER_SETUP_H

// ---------------- Driver ----------------
#define ILI9341_2_DRIVER

// ---------------- Pins ----------------
#define TFT_MISO 12
#define TFT_MOSI 13
#define TFT_SCLK 14

#define TFT_CS   15
#define TFT_DC   2
#define TFT_RST  -1

// ---------------- SPI Frequencies ----------------
// CYD panels usually like 40MHz writes; if you see tearing/noise, drop to 27MHz.
#define SPI_FREQUENCY       40000000
#define SPI_READ_FREQUENCY  20000000
#define SPI_TOUCH_FREQUENCY  2500000

// ---------------- Fonts ----------------
#define LOAD_GLCD
#define LOAD_FONT2
#define LOAD_FONT4
#define LOAD_FONT6
#define LOAD_FONT7
#define LOAD_FONT8
#define LOAD_GFXFF

// Smooth font support (optional)
#define SMOOTH_FONT

#endif // USER_SETUP_H
