# Source: Generated by ChatGPT
# bootstrap_tokyo_neon_ui.ps1
# Purpose: Apply/overwrite a Tokyo Neon (Wardrive Analyzer-style) UI shell into an existing Android Studio Compose project.
# Run from your repo root (e.g., C:\ESP32\CYDCompanion).

$ErrorActionPreference = "Stop"

function Write-Info($msg) { Write-Host "[INFO] $msg" -ForegroundColor Cyan }
function Write-Warn($msg) { Write-Host "[WARN] $msg" -ForegroundColor Yellow }
function Write-Err ($msg) { Write-Host "[ERR ] $msg" -ForegroundColor Red }

$root = Get-Location

# Detect Android Gradle project layout
$settings = Join-Path $root "settings.gradle.kts"
$appDir   = Join-Path $root "app"
$appGradle= Join-Path $appDir "build.gradle.kts"

if (!(Test-Path $settings) -or !(Test-Path $appDir) -or !(Test-Path $appGradle)) {
  Write-Warn "I don't see an Android Studio Gradle project here yet."
  Write-Host ""
  Write-Host "Do this once, THEN rerun the script:" -ForegroundColor Green
  Write-Host "  1) Android Studio -> New Project -> Empty Activity (Compose)" -ForegroundColor Green
  Write-Host "  2) Set project location to: $root" -ForegroundColor Green
  Write-Host "  3) Package name: com.example.cydcompanion" -ForegroundColor Green
  Write-Host "  4) Min SDK: 26" -ForegroundColor Green
  Write-Host ""
  Write-Err "Aborting without changes."
  exit 1
}

# Backup folder
$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$backupDir = Join-Path $root "_backup_tokyo_neon_$timestamp"
New-Item -ItemType Directory -Force -Path $backupDir | Out-Null

Write-Info "Backing up key files to $backupDir"
$backupTargets = @(
  "settings.gradle.kts",
  "app/build.gradle.kts",
  "app/src/main/AndroidManifest.xml"
)
foreach ($t in $backupTargets) {
  $p = Join-Path $root $t
  if (Test-Path $p) {
    $dest = Join-Path $backupDir ($t -replace "/", "_")
    Copy-Item -Force $p $dest
  }
}

function Ensure-Dir($path) {
  if (!(Test-Path $path)) { New-Item -ItemType Directory -Force -Path $path | Out-Null }
}

function Write-FileUtf8($path, $content) {
  Ensure-Dir (Split-Path $path -Parent)
  Set-Content -Path $path -Value $content -Encoding UTF8
}

# --- settings.gradle.kts (safe overwrite) ---
Write-Info "Writing settings.gradle.kts"
Write-FileUtf8 $settings @"
# Source: Generated by ChatGPT
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "CYDCompanion"
include(":app")
"@

# --- Root build.gradle.kts (minimal) ---
$rootBuild = Join-Path $root "build.gradle.kts"
Write-Info "Writing root build.gradle.kts"
Write-FileUtf8 $rootBuild @"
# Source: Generated by ChatGPT
// Keep root clean; module(s) declare plugins/versions.
plugins { }
"@

# --- gradle.properties (sane defaults) ---
$gradleProps = Join-Path $root "gradle.properties"
Write-Info "Writing gradle.properties"
Write-FileUtf8 $gradleProps @"
# Source: Generated by ChatGPT
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
"@

# --- app/build.gradle.kts ---
Write-Info "Writing app/build.gradle.kts"
Write-FileUtf8 $appGradle @"
# Source: Generated by ChatGPT
plugins {
    id("com.android.application") version "8.5.2"
    id("org.jetbrains.kotlin.android") version "1.9.24"
}

android {
    namespace = "com.example.cydcompanion"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.example.cydcompanion"
        minSdk = 26
        targetSdk = 34
        versionCode = 1
        versionName = "0.1.0"
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = "17" }

    buildFeatures { compose = true }
    composeOptions { kotlinCompilerExtensionVersion = "1.5.14" }

    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

dependencies {
    val composeBom = platform("androidx.compose:compose-bom:2024.06.00")
    implementation(composeBom)
    androidTestImplementation(composeBom)

    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.4")
    implementation("androidx.activity:activity-compose:1.9.1")

    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-tooling-preview")
    debugImplementation("androidx.compose.ui:ui-tooling")

    implementation("androidx.compose.material3:material3:1.2.1")
    implementation("androidx.compose.material:material-icons-extended")

    implementation("androidx.navigation:navigation-compose:2.7.7")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1")
}
"@

# --- AndroidManifest.xml ---
$manifest = Join-Path $root "app/src/main/AndroidManifest.xml"
Write-Info "Writing AndroidManifest.xml"
Write-FileUtf8 $manifest @"
<!-- Source: Generated by ChatGPT -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application
        android:allowBackup="true"
        android:label="CYD Companion"
        android:supportsRtl="true"
        android:theme="@style/Theme.CYDCompanion">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
"@

# --- Kotlin sources ---
$pkgRoot = Join-Path $root "app/src/main/java/com/example/cydcompanion"
Ensure-Dir $pkgRoot
Ensure-Dir (Join-Path $pkgRoot "ui")
Ensure-Dir (Join-Path $pkgRoot "ui/theme")
Ensure-Dir (Join-Path $pkgRoot "ui/background")
Ensure-Dir (Join-Path $pkgRoot "data")
Ensure-Dir (Join-Path $pkgRoot "domain")

# MainActivity.kt
Write-Info "Writing MainActivity.kt + UI shell"
Write-FileUtf8 (Join-Path $pkgRoot "MainActivity.kt") @"
/* Source: Generated by ChatGPT */
package com.example.cydcompanion

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import com.example.cydcompanion.ui.AppRoot
import com.example.cydcompanion.ui.theme.TokyoNeonTheme

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            TokyoNeonTheme {
                AppRoot()
            }
        }
    }
}
"@

# Domain models
Write-FileUtf8 (Join-Path $pkgRoot "domain/Models.kt") @"
/* Source: Generated by ChatGPT */
package com.example.cydcompanion.domain

data class ConnectionState(
    val status: Status,
    val deviceName: String? = null,
    val rssi: Int? = null,
    val mtu: Int? = null,
    val uptimeSec: Int? = null
) {
    enum class Status { DISCONNECTED, SCANNING, CONNECTING, CONNECTED }
}

data class SessionSummary(
    val id: String,
    val startedAt: String,
    val records: Int,
    val warnings: Int,
    val notes: String
)

data class ConsoleLine(
    val ts: String,
    val level: Level,
    val tag: String,
    val msg: String
) {
    enum class Level { INFO, WARN, ERROR }
}
"@

# Fake repository
Write-FileUtf8 (Join-Path $pkgRoot "data/FakeCydRepository.kt") @"
/* Source: Generated by ChatGPT */
package com.example.cydcompanion.data

import com.example.cydcompanion.domain.ConnectionState
import com.example.cydcompanion.domain.ConsoleLine
import com.example.cydcompanion.domain.SessionSummary
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.flow
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import kotlin.random.Random

class FakeCydRepository {

    private val _conn = MutableStateFlow(
        ConnectionState(status = ConnectionState.Status.SCANNING, deviceName = "CYD-NEON")
    )
    val connection: Flow<ConnectionState> = _conn

    val sessions: Flow<List<SessionSummary>> = flow {
        val seed = listOf(
            SessionSummary("run_001", "2026-02-16 07:12", 1284, 3, "Baseline pass"),
            SessionSummary("run_002", "2026-02-16 07:48", 904, 0, "Clean"),
            SessionSummary("run_003", "2026-02-16 08:05", 2211, 7, "Spicy signal soup")
        )
        emit(seed)
    }

    val console: Flow<ConsoleLine> = flow {
        val sdf = SimpleDateFormat("HH:mm:ss.SSS", Locale.US)
        var i = 0
        while (true) {
            delay(180)
            i++
            val lvl = when {
                i % 29 == 0 -> ConsoleLine.Level.ERROR
                i % 11 == 0 -> ConsoleLine.Level.WARN
                else -> ConsoleLine.Level.INFO
            }
            val tag = listOf("CYD", "BLE", "UI", "CAP", "SYS").random()
            val msg = when (lvl) {
                ConsoleLine.Level.INFO -> listOf(
                    "Heartbeat OK",
                    "Frame parsed",
                    "Queue depth=${'$'}{Random.nextInt(0, 12)}",
                    "RX bytes +${'$'}{Random.nextInt(20, 240)}",
                    "Touch preset locked: #5"
                ).random()
                ConsoleLine.Level.WARN -> listOf(
                    "RSSI wobble detected",
                    "Retrying write",
                    "Dropped frame (simulated)",
                    "Clock drift +2ms"
                ).random()
                ConsoleLine.Level.ERROR -> listOf(
                    "Simulated fault: CRC mismatch",
                    "Simulated fault: buffer overrun",
                    "Simulated fault: stale session"
                ).random()
            }
            emit(ConsoleLine(ts = sdf.format(Date()), level = lvl, tag = tag, msg = msg))
        }
    }

    suspend fun simulateConnectionCycle() {
        _conn.emit(ConnectionState(ConnectionState.Status.SCANNING, "CYD-NEON"))
        delay(900)
        _conn.emit(ConnectionState(ConnectionState.Status.CONNECTING, "CYD-NEON"))
        delay(1200)
        _conn.emit(ConnectionState(ConnectionState.Status.CONNECTED, "CYD-NEON", rssi = -53, mtu = 185, uptimeSec = 42))

        // jitter
        var up = 42
        while (true) {
            delay(1200)
            up += 1
            _conn.emit(ConnectionState(ConnectionState.Status.CONNECTED, "CYD-NEON", rssi = -48 - Random.nextInt(0, 18), mtu = 185, uptimeSec = up))
        }
    }
}
"@

# UI - navigation and root
Write-FileUtf8 (Join-Path $pkgRoot "ui/AppRoot.kt") @"
/* Source: Generated by ChatGPT */
package com.example.cydcompanion.ui

import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Analytics
import androidx.compose.material.icons.filled.CloudUpload
import androidx.compose.material.icons.filled.Gamepad
import androidx.compose.material.icons.filled.PlayArrow
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.navigation.compose.*
import com.example.cydcompanion.data.FakeCydRepository
import com.example.cydcompanion.ui.background.TokyoNeonBackdrop
import kotlinx.coroutines.launch

private sealed class Tab(val route: String, val label: String, val icon: @Composable () -> Unit) {
    data object Live : Tab("live", "Live", { Icon(Icons.Filled.PlayArrow, contentDescription = null) })
    data object Analyze : Tab("analyze", "Analyze", { Icon(Icons.Filled.Analytics, contentDescription = null) })
    data object Control : Tab("control", "Control", { Icon(Icons.Filled.Gamepad, contentDescription = null) })
    data object Export : Tab("export", "Export", { Icon(Icons.Filled.CloudUpload, contentDescription = null) })
}

@Composable
fun AppRoot() {
    val nav = rememberNavController()
    val repo = remember { FakeCydRepository() }
    val scope = rememberCoroutineScope()

    LaunchedEffect(Unit) {
        scope.launch { repo.simulateConnectionCycle() }
    }

    val tabs = listOf(Tab.Live, Tab.Analyze, Tab.Control, Tab.Export)

    TokyoNeonBackdrop {
        Scaffold(
            containerColor = MaterialTheme.colorScheme.background.copy(alpha = 0.0f),
            bottomBar = {
                NavigationBar(
                    containerColor = MaterialTheme.colorScheme.surface.copy(alpha = 0.55f),
                    tonalElevation = 0.dp
                ) {
                    val current by nav.currentBackStackEntryAsState()
                    val route = current?.destination?.route
                    tabs.forEach { tab ->
                        NavigationBarItem(
                            selected = route == tab.route,
                            onClick = { nav.navigate(tab.route) { launchSingleTop = true } },
                            icon = tab.icon,
                            label = { Text(tab.label) }
                        )
                    }
                }
            }
        ) { padding ->
            Box(modifier = Modifier.fillMaxSize()) {
                NavHost(navController = nav, startDestination = Tab.Live.route) {
                    composable(Tab.Live.route) { LiveScreen(repo = repo) }
                    composable(Tab.Analyze.route) { AnalyzeScreen(repo = repo) }
                    composable(Tab.Control.route) { ControlScreen(repo = repo) }
                    composable(Tab.Export.route) { ExportScreen(repo = repo) }
                }
            }
        }
    }
}
"@

# LiveScreen
Write-FileUtf8 (Join-Path $pkgRoot "ui/LiveScreen.kt") @"
/* Source: Generated by ChatGPT */
package com.example.cydcompanion.ui

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import com.example.cydcompanion.data.FakeCydRepository
import com.example.cydcompanion.domain.ConnectionState
import com.example.cydcompanion.domain.ConsoleLine
import kotlinx.coroutines.flow.collectLatest

@Composable
fun LiveScreen(repo: FakeCydRepository) {
    val conn by produceState<ConnectionState>(
        initialValue = ConnectionState(ConnectionState.Status.SCANNING, "CYD-NEON")
    ) {
        repo.connection.collectLatest { value = it }
    }

    val lines = remember { mutableStateListOf<ConsoleLine>() }
    LaunchedEffect(Unit) {
        repo.console.collectLatest {
            if (lines.size > 240) lines.removeRange(0, 40)
            lines.add(it)
        }
    }

    ScreenScaffold(title = "LIVE LINK") {
        NeonCard {
            Column(Modifier.fillMaxWidth()) {
                Text("CYD STATUS", style = MaterialTheme.typography.titleMedium)
                Spacer(Modifier.height(8.dp))

                val status = conn.status
                val statusText = when (status) {
                    ConnectionState.Status.DISCONNECTED -> "DISCONNECTED"
                    ConnectionState.Status.SCANNING -> "SCANNING…"
                    ConnectionState.Status.CONNECTING -> "CONNECTING…"
                    ConnectionState.Status.CONNECTED -> "CONNECTED"
                }
                Text(statusText, style = MaterialTheme.typography.headlineSmall)

                Spacer(Modifier.height(8.dp))
                Row(horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                    AssistChip(onClick = {}, label = { Text(conn.deviceName ?: "—") })
                    AssistChip(onClick = {}, label = { Text("RSSI ${'$'}{conn.rssi ?: "—"}") })
                    AssistChip(onClick = {}, label = { Text("MTU ${'$'}{conn.mtu ?: "—"}") })
                    AssistChip(onClick = {}, label = { Text("UP ${'$'}{conn.uptimeSec ?: 0}s") })
                }

                Spacer(Modifier.height(12.dp))
                Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                    NeonButton(text = "START", onClick = {})
                    NeonButton(text = "STOP", onClick = {}, isDanger = true)
                }
            }
        }

        Spacer(Modifier.height(14.dp))

        NeonCard {
            Column(Modifier.fillMaxWidth()) {
                Text("CONSOLE", style = MaterialTheme.typography.titleMedium)
                Spacer(Modifier.height(8.dp))
                LazyColumn(
                    modifier = Modifier
                        .fillMaxWidth()
                        .heightIn(min = 220.dp, max = 520.dp)
                ) {
                    itemsIndexed(lines) { _, line ->
                        val prefix = "[${'$'}{line.ts}] ${'$'}{line.level} ${'$'}{line.tag}: "
                        Text(
                            text = prefix + line.msg,
                            style = MaterialTheme.typography.bodySmall,
                            fontFamily = FontFamily.Monospace
                        )
                    }
                }
            }
        }
    }
}
"@

# AnalyzeScreen
Write-FileUtf8 (Join-Path $pkgRoot "ui/AnalyzeScreen.kt") @"
/* Source: Generated by ChatGPT */
package com.example.cydcompanion.ui

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.example.cydcompanion.data.FakeCydRepository
import com.example.cydcompanion.domain.SessionSummary
import kotlinx.coroutines.flow.collectLatest

@Composable
fun AnalyzeScreen(repo: FakeCydRepository) {
    val sessions by produceState<List<SessionSummary>>(initialValue = emptyList()) {
        repo.sessions.collectLatest { value = it }
    }

    ScreenScaffold(title = "ANALYZE") {
        NeonCard {
            Column(Modifier.fillMaxWidth()) {
                Text("SESSION SUMMARY", style = MaterialTheme.typography.titleMedium)
                Spacer(Modifier.height(10.dp))
                Row(horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                    StatChip("Runs", sessions.size.toString())
                    StatChip("Records", sessions.sumOf { it.records }.toString())
                    StatChip("Warnings", sessions.sumOf { it.warnings }.toString())
                }
            }
        }

        Spacer(Modifier.height(14.dp))

        NeonCard {
            Column(Modifier.fillMaxWidth()) {
                Text("RUNS", style = MaterialTheme.typography.titleMedium)
                Spacer(Modifier.height(8.dp))
                LazyColumn(modifier = Modifier.fillMaxWidth()) {
                    items(sessions) { s ->
                        ListItem(
                            headlineContent = { Text("${'$'}{s.id}  ·  ${'$'}{s.startedAt}") },
                            supportingContent = { Text("${'$'}{s.records} records · ${'$'}{s.warnings} warnings · ${'$'}{s.notes}") }
                        )
                        Divider(color = MaterialTheme.colorScheme.outline.copy(alpha = 0.35f))
                    }
                }
            }
        }

        Spacer(Modifier.height(14.dp))

        NeonCard {
            Column(Modifier.fillMaxWidth()) {
                Text("CHARTS (PLACEHOLDERS)", style = MaterialTheme.typography.titleMedium)
                Spacer(Modifier.height(10.dp))
                Text("Timeline · RSSI distribution · Anomaly markers — wired once BLE/data schema lands.")
            }
        }
    }
}
"@

# ControlScreen
Write-FileUtf8 (Join-Path $pkgRoot "ui/ControlScreen.kt") @"
/* Source: Generated by ChatGPT */
package com.example.cydcompanion.ui

import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.example.cydcompanion.data.FakeCydRepository

@Composable
fun ControlScreen(repo: FakeCydRepository) {
    var brightness by remember { mutableFloatStateOf(0.85f) }
    var mode by remember { mutableStateOf("Wardrive") }

    ScreenScaffold(title = "CONTROL") {
        NeonCard {
            Column(Modifier.fillMaxWidth()) {
                Text("REMOTE CONTROL (MOCK)", style = MaterialTheme.typography.titleMedium)
                Spacer(Modifier.height(10.dp))

                Text("Touch mapping default: PRESET #5")
                Spacer(Modifier.height(10.dp))

                Text("Brightness")
                Slider(value = brightness, onValueChange = { brightness = it })

                Spacer(Modifier.height(10.dp))

                Text("Mode")
                Row(horizontalArrangement = Arrangement.spacedBy(10.dp)) {
                    FilterChip(selected = mode == "Wardrive", onClick = { mode = "Wardrive" }, label = { Text("Wardrive") })
                    FilterChip(selected = mode == "Target", onClick = { mode = "Target" }, label = { Text("Target") })
                    FilterChip(selected = mode == "Weather", onClick = { mode = "Weather" }, label = { Text("Weather") })
                }

                Spacer(Modifier.height(14.dp))
                Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                    NeonButton(text = "PING", onClick = {})
                    NeonButton(text = "GET STATUS", onClick = {})
                }
            }
        }
    }
}
"@

# ExportScreen
Write-FileUtf8 (Join-Path $pkgRoot "ui/ExportScreen.kt") @"
/* Source: Generated by ChatGPT */
package com.example.cydcompanion.ui

import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.example.cydcompanion.data.FakeCydRepository

@Composable
fun ExportScreen(repo: FakeCydRepository) {
    ScreenScaffold(title = "EXPORT") {
        NeonCard {
            Column(Modifier.fillMaxWidth()) {
                Text("RUN BUNDLE", style = MaterialTheme.typography.titleMedium)
                Spacer(Modifier.height(10.dp))
                Text("This will export sessions/records once the on-device schema is finalized.")
                Spacer(Modifier.height(14.dp))
                Row(horizontalArrangement = Arrangement.spacedBy(12.dp)) {
                    NeonButton(text = "EXPORT JSON", onClick = {})
                    NeonButton(text = "EXPORT CSV", onClick = {})
                }
            }
        }
    }
}
"@

# Shared UI bits
Write-FileUtf8 (Join-Path $pkgRoot "ui/UiBits.kt") @"
/* Source: Generated by ChatGPT */
package com.example.cydcompanion.ui

import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp

@Composable
fun ScreenScaffold(title: String, content: @Composable ColumnScope.() -> Unit) {
    Column(
        Modifier
            .fillMaxSize()
            .padding(horizontal = 14.dp, vertical = 14.dp)
    ) {
        Text(title, style = MaterialTheme.typography.headlineMedium)
        Spacer(Modifier.height(12.dp))
        content()
    }
}

@Composable
fun NeonCard(content: @Composable ColumnScope.() -> Unit) {
    Card(
        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface.copy(alpha = 0.52f)),
        border = CardDefaults.outlinedCardBorder(enabled = true),
        modifier = Modifier.fillMaxWidth()
    ) {
        Column(Modifier.padding(14.dp), content = content)
    }
}

@Composable
fun NeonButton(text: String, onClick: () -> Unit, isDanger: Boolean = false) {
    val colors = if (isDanger) {
        ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.error.copy(alpha = 0.85f))
    } else {
        ButtonDefaults.buttonColors(containerColor = MaterialTheme.colorScheme.primary.copy(alpha = 0.85f))
    }
    Button(onClick = onClick, colors = colors) { Text(text) }
}

@Composable
fun StatChip(label: String, value: String) {
    AssistChip(onClick = {}, label = { Text("${label}: ${value}") })
}
"@

# Theme - Tokyo neon
Write-FileUtf8 (Join-Path $pkgRoot "ui/theme/Theme.kt") @"
/* Source: Generated by ChatGPT */
package com.example.cydcompanion.ui.theme

import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color

private val TokyoNeon = darkColorScheme(
    background = Color(0xFF05040A),   // inky
    surface = Color(0xFF0B0A14),      // deep indigo
    primary = Color(0xFF00E5FF),      // neon cyan
    secondary = Color(0xFFFF2BD6),    // neon magenta
    tertiary = Color(0xFF8A5CFF),     // violet glow
    outline = Color(0xFF2C2A3A),
    error = Color(0xFFFF3B3B)
)

@Composable
fun TokyoNeonTheme(content: @Composable () -> Unit) {
    MaterialTheme(
        colorScheme = TokyoNeon,
        typography = TypographyTokyoNeon,
        content = content
    )
}
"@

Write-FileUtf8 (Join-Path $pkgRoot "ui/theme/Type.kt") @"
/* Source: Generated by ChatGPT */
package com.example.cydcompanion.ui.theme

import androidx.compose.material3.Typography
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.sp

val TypographyTokyoNeon = Typography(
    headlineMedium = TextStyle(
        fontFamily = FontFamily.SansSerif,
        fontSize = 26.sp
    ),
    titleMedium = TextStyle(
        fontFamily = FontFamily.SansSerif,
        fontSize = 16.sp
    ),
    bodySmall = TextStyle(
        fontFamily = FontFamily.Monospace,
        fontSize = 12.sp
    )
)
"@

# Background - animated grid + rain shimmer
Write-Info "Writing animated Tokyo neon background"
Write-FileUtf8 (Join-Path $pkgRoot "ui/background/TokyoNeonBackdrop.kt") @"
/* Source: Generated by ChatGPT */
package com.example.cydcompanion.ui.background

import androidx.compose.foundation.Canvas
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.drawscope.Stroke
import kotlinx.coroutines.delay
import kotlin.math.sin

@Composable
fun TokyoNeonBackdrop(content: @Composable () -> Unit) {
    var t by remember { mutableFloatStateOf(0f) }
    LaunchedEffect(Unit) {
        while (true) {
            delay(16)
            t += 0.016f
        }
    }

    Box(Modifier.fillMaxSize()) {
        Canvas(Modifier.fillMaxSize()) {
            val w = size.width
            val h = size.height

            // Inky base wash
            drawRect(Color(0xFF05040A))

            // Horizon
            val horizonY = h * 0.42f

            // Neon grid lines (perspective)
            val lines = 18
            val spacing = w / lines
            val drift = (sin(t * 0.7f) * 8f)

            // Vertical-ish lines to horizon
            for (i in -2..(lines + 2)) {
                val x = i * spacing + drift
                val x2 = w * 0.5f + (x - w * 0.5f) * 0.06f
                drawLine(
                    color = Color(0x3300E5FF),
                    start = Offset(x, h),
                    end = Offset(x2, horizonY),
                    strokeWidth = 2f
                )
            }

            // Horizontal perspective lines
            val bands = 22
            for (i in 0..bands) {
                val p = i / bands.toFloat()
                val y = horizonY + (h - horizonY) * (p * p)
                val alpha = (0.08f * (1f - p)) + 0.02f
                drawLine(
                    color = Color(0xFFFF2BD6).copy(alpha = alpha),
                    start = Offset(0f, y),
                    end = Offset(w, y),
                    strokeWidth = 2f
                )
            }

            // Subtle rain shimmer streaks
            val drops = 90
            val speed = 220f
            for (i in 0 until drops) {
                val seed = i * 37.73f
                val x = (seed * 19.91f) % w
                val y = ((seed * 7.13f) + (t * speed * 60f)) % h
                val len = 18f + (seed % 22f)
                drawLine(
                    color = Color(0x2200E5FF),
                    start = Offset(x, y),
                    end = Offset(x + 4f, y + len),
                    strokeWidth = 1.6f
                )
            }

            // Neon rim vignette
            drawRect(
                color = Color(0x1A8A5CFF),
                style = Stroke(width = 18f)
            )
        }

        content()
    }
}
"@

# README
Write-Info "Writing README.md"
Write-FileUtf8 (Join-Path $root "README.md") @"
# CYDCompanion (Tokyo Neon UI-first)

**Source:** Generated by ChatGPT

UI-first Android companion app shell for ESP32 CYD projects with a **Tokyo Neon at night** aesthetic:
- Inky indigo base
- Neon cyan/magenta accents
- Glass panels
- Animated grid horizon + subtle rain shimmer
- Tabs: Live / Analyze / Control / Export
- Fake repository streaming console + simulated connection state

## How to run
1. Open this folder in **Android Studio**
2. Let Gradle sync
3. Run on emulator or device (min SDK 26)

## Next step (BLE)
Replace `FakeCydRepository` with a BLE-backed repository using:
- Data notify characteristic (CYD -> Android)
- Command write characteristic (Android -> CYD)
- Start with newline-delimited JSON for debuggability

## CYD baseline note
Touch mapping default should remain **PRESET #5** for landscape USB-right orientation.
"@

Write-Host ""
Write-Info "Done. Open the project in Android Studio and Run."
Write-Info "Backup stored at: $backupDir"
